import { useMutation, useQuery } from "@apollo/client/react";
import { useSearchParams } from "react-router-dom";
import { CANCEL_PROCESSING_JOB, MANAGE_PROCESSING_JOBS, RETRY_PROCESSING_JOB } from "../api/manage";
import type { ManageProcessingJobPage } from "./types";

const statuses = ["ALL", "PENDING", "RUNNING", "RETRY_WAIT", "FAILED", "COMPLETED", "CANCELLED"];
export function ManageTasksPage() {
  const [parameters, setParameters] = useSearchParams(); const status = statuses.includes(parameters.get("status") || "") ? parameters.get("status")! : "ALL"; const page = Math.max(1, Number(parameters.get("page")) || 1);
  const query = useQuery<{ manageProcessingJobs: ManageProcessingJobPage }>(MANAGE_PROCESSING_JOBS, { variables: { status, page }, pollInterval: 2000 });
  const [cancel] = useMutation(CANCEL_PROCESSING_JOB); const [retry] = useMutation(RETRY_PROCESSING_JOB); const data = query.data?.manageProcessingJobs;
  async function act(kind: "cancel" | "retry", id: number) { if (kind === "cancel") await cancel({ variables: { id } }); else await retry({ variables: { id } }); await query.refetch(); }
  return <main className="manage-page"><header className="manage-heading"><div><p>PERSISTENT LEASE QUEUE</p><h2>Tasks</h2></div><span>{data?.totalItems ?? 0} jobs</span></header><nav className="task-filters">{statuses.map((value) => <button type="button" className={value === status ? "is-active" : ""} key={value} onClick={() => setParameters({ status: value, page: "1" })}>{value}</button>)}</nav>{query.error ? <p className="manage-message">Unable to load tasks.</p> : null}<div className="manage-table-wrap"><table className="manage-table task-table"><thead><tr><th>Status</th><th>Kind / variant</th><th>Gallery / Item</th><th>Attempts</th><th>Error</th><th>Updated</th><th>Action</th></tr></thead><tbody>{data?.items.map((job) => { const active = ["PENDING", "RUNNING", "RETRY_WAIT", "PAUSED"].includes(job.status); return <tr key={job.id}><td><span className={`state state--${job.status.toLowerCase()}`}>{job.status}</span></td><td>{job.kind}<small>{job.variant || "—"}</small></td><td>{job.galleryID ?? "—"}<small>{job.itemUUID || "—"}</small></td><td>{job.attemptCount} / {job.maxAttempts}</td><td>{job.lastErrorCode || "—"}</td><td>{new Date(job.updatedAt).toLocaleString()}</td><td>{active ? <button type="button" onClick={() => act("cancel", job.id)}>Cancel</button> : <button type="button" onClick={() => act("retry", job.id)}>Retry</button>}</td></tr>; })}</tbody></table></div>{data && data.totalPages > 1 ? <nav className="manage-pagination"><button disabled={page <= 1} onClick={() => setParameters({ status, page: String(page - 1) })}>Previous</button><span>{page} / {data.totalPages}</span><button disabled={page >= data.totalPages} onClick={() => setParameters({ status, page: String(page + 1) })}>Next</button></nav> : null}</main>;
}
