import { useMutation, useQuery } from "@apollo/client/react";
import { type FormEvent, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ADD_COSER_SOCIAL_ACCOUNT, CREATE_CORE_ENTITY, MANAGE_CORE_ENTITIES, MANAGE_CORE_ENTITY, MANAGE_COSER_MANIFEST, PULL_COSER_MANIFEST, PUSH_COSER_MANIFEST, REPLACE_TAG_PARENTS, RESOLVE_COSER_MANIFEST, UPDATE_CORE_ENTITY } from "../api/manage";
import { ManageEntitySelector } from "./ManageEntitySelector";
import { ManageEntityLifecyclePanel } from "./ManageEntityLifecyclePanel";
import { ManageCoserAssetsPanel } from "./ManageCoserAssetsPanel";
import { ManageCoserMetadataImport } from "./ManageCoserMetadataImport";
import type { ManageCoreEntity, ManageCoreEntityPage, ManageCoserManifestState } from "./types";

type Kind = ManageCoreEntity["kind"];
const kinds: Kind[] = ["WORK", "CHARACTER", "TAG"];
const blank = (kind: Kind): ManageCoreEntity => ({ kind, uuid: "", name: "", sortName: "", aliases: [], slug: "", metadataRevision: 0, profileSummary: "", biography: "", countryOrRegion: "", useInRecommendation: true, socialAccounts: [], parents: [] });
export const parseAliases = (value: string) => value.split("/").map((alias) => alias.trim()).filter(Boolean);
export const socialPlatformOptions = [
  ["instagram", "Instagram"], ["twitter", "Twitter / X"], ["weibo", "Weibo"],
  ["bilibili", "Bilibili"], ["xiaohongshu", "Xiaohongshu"], ["douyin", "Douyin"],
  ["tiktok", "TikTok"], ["youtube", "YouTube"], ["pixiv", "Pixiv"],
  ["facebook", "Facebook"], ["bluesky", "Bluesky"], ["patreon", "Patreon"],
  ["fanbox", "FANBOX"], ["website", "Website"],
] as const;

function isAbsoluteHTTPURL(value: string) {
  try {
    const parsed = new URL(value);
    return (parsed.protocol === "http:" || parsed.protocol === "https:") &&
      parsed.host !== "" && parsed.username === "" && parsed.password === "";
  } catch {
    return false;
  }
}

export function ManageCoreEntitiesPage({ coserOnly = false }: { coserOnly?: boolean }) {
  const [parameters, setParameters] = useSearchParams(); const kind: Kind = coserOnly ? "COSER" : kinds.includes(parameters.get("kind") as Kind) ? parameters.get("kind") as Kind : "WORK"; const page = Math.max(1, Number(parameters.get("page")) || 1); const selected = parameters.get("uuid") || "";
  const [draft, setDraft] = useState<ManageCoreEntity>(blank(kind)); const [aliasText, setAliasText] = useState(""); const [message, setMessage] = useState(""); const [coserTab, setCoserTab] = useState("profile");
  const [account, setAccount] = useState({ platformKey: "", label: "", handle: "", url: "https://", status: "ACTIVE", visible: true, position: "1024" });
  const [conflictChoices, setConflictChoices] = useState<Record<string, "DATABASE" | "FILE">>({});
  const listQuery = useQuery<{ manageCoreEntities: ManageCoreEntityPage }>(MANAGE_CORE_ENTITIES, { variables: { kind, page } }); const detailQuery = useQuery<{ manageCoreEntity: ManageCoreEntity }>(MANAGE_CORE_ENTITY, { variables: { kind, uuid: selected }, skip: !selected, fetchPolicy: "network-only" });
  const [create, createState] = useMutation<{ createCoreEntity: ManageCoreEntity }>(CREATE_CORE_ENTITY); const [update, updateState] = useMutation<{ updateCoreEntity: ManageCoreEntity }>(UPDATE_CORE_ENTITY); const [addSocial, addSocialState] = useMutation<{ addCoserSocialAccount: ManageCoreEntity }>(ADD_COSER_SOCIAL_ACCOUNT);
  const [replaceTagParents, replaceTagParentsState] = useMutation<{ replaceTagParents: ManageCoreEntity }>(REPLACE_TAG_PARENTS);
  const manifestQuery = useQuery<{ manageCoserManifest: ManageCoserManifestState }>(MANAGE_COSER_MANIFEST, { variables: { coserUUID: draft?.uuid || selected }, skip: kind !== "COSER" || coserTab !== "manifest" || !(draft?.uuid || selected), fetchPolicy: "network-only" });
  const [pushManifest, pushManifestState] = useMutation(PUSH_COSER_MANIFEST); const [pullManifest, pullManifestState] = useMutation(PULL_COSER_MANIFEST); const [resolveManifest, resolveManifestState] = useMutation(RESOLVE_COSER_MANIFEST);
  useEffect(() => { setDraft(detailQuery.data?.manageCoreEntity ?? blank(kind)); }, [detailQuery.data, kind, selected]);
  useEffect(() => { setAliasText(draft.aliases.join(" / ")); }, [draft.kind, draft.metadataRevision, draft.uuid]);
  const data = listQuery.data?.manageCoreEntities;
  function input(value = draft) { return { kind: value.kind, name: value.name, sortName: value.sortName, aliases: parseAliases(aliasText), workUUID: value.kind === "CHARACTER" ? value.workUUID || null : null, profileSummary: value.profileSummary, biography: value.biography, countryOrRegion: value.countryOrRegion, useInRecommendation: value.useInRecommendation }; }
  const entityValid = draft.name.trim() !== "" && (draft.kind !== "CHARACTER" || Boolean(draft.workUUID));
  const socialAccountValid = /^[a-z0-9][a-z0-9_-]{0,63}$/.test(account.platformKey) && isAbsoluteHTTPURL(account.url);
  async function save(event: FormEvent) { event.preventDefault(); if (!entityValid) return; setMessage(""); try { if (draft.uuid) { const result = await update({ variables: { uuid: draft.uuid, expectedMetadataRevision: draft.metadataRevision, input: input() } }); if (!result.data) throw new Error("Server did not return the saved entity"); setDraft(result.data.updateCoreEntity); } else { const result = await create({ variables: { input: input() } }); if (!result.data) throw new Error("Server did not return the created entity"); setDraft(result.data.createCoreEntity); setParameters({ ...(coserOnly ? {} : { kind }), uuid: result.data.createCoreEntity.uuid }); } await listQuery.refetch(); setMessage("Saved"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save entity"); } }
  async function addAccount(event: FormEvent) { event.preventDefault(); if (!draft.uuid || !socialAccountValid) return; setMessage(""); try { const result = await addSocial({ variables: { coserUUID: draft.uuid, expectedMetadataRevision: draft.metadataRevision, input: account } }); if (!result.data) throw new Error("Server did not return the saved social account"); setDraft(result.data.addCoserSocialAccount); setAccount({ ...account, platformKey: "", label: "", handle: "", url: "https://", position: String((draft.socialAccounts.length + 2) * 1024) }); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add social account"); } }
  async function runCoserManifest(action: "PUSH" | "PULL") { if (!draft.uuid) return; setMessage(""); try { const call = action === "PUSH" ? pushManifest : pullManifest; await call({ variables: { coserUUID: draft.uuid, expectedMetadataRevision: draft.metadataRevision } }); await detailQuery.refetch(); await manifestQuery.refetch(); setMessage(`Coser Manifest ${action} completed`); } catch (error) { setMessage(error instanceof Error ? error.message : `Coser Manifest ${action} failed`); } }
  async function resolveCoserManifest() { const conflicts = manifestQuery.data?.manageCoserManifest.conflicts || []; if (!draft.uuid || conflicts.some((conflict) => !conflictChoices[conflict.path])) { setMessage("Choose Database or File for every conflict"); return; } setMessage(""); try { await resolveManifest({ variables: { coserUUID: draft.uuid, expectedMetadataRevision: draft.metadataRevision, choices: conflicts.map((conflict) => ({ path: conflict.path, choice: conflictChoices[conflict.path] })) } }); setConflictChoices({}); await detailQuery.refetch(); await manifestQuery.refetch(); setMessage("Coser Manifest conflicts resolved and pulled"); } catch (error) { setMessage(error instanceof Error ? error.message : "Coser Manifest conflict resolution failed"); } }
  async function saveTagParents() { if (draft.kind !== "TAG" || !draft.uuid) return; const expected = new Map<string, number>(); for (const parent of detailQuery.data?.manageCoreEntity.parents || []) expected.set(parent.uuid, parent.metadataRevision); for (const parent of draft.parents) expected.set(parent.uuid, parent.metadataRevision); setMessage(""); try { const result = await replaceTagParents({ variables: { childUUID: draft.uuid, expectedChildRevision: draft.metadataRevision, parents: draft.parents.map((parent, index) => ({ uuid: parent.uuid, position: String((index + 1) * 1024) })), expectedParents: Array.from(expected, ([uuid, metadataRevision]) => ({ uuid, metadataRevision })) } }); if (result.data) setDraft(result.data.replaceTagParents); await detailQuery.refetch(); await listQuery.refetch(); setMessage("Tag parent DAG saved"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save Tag parents"); } }
  async function merged(target: ManageCoreEntity, completionWarning?: string | null) { setDraft(target); setParameters({ ...(coserOnly ? {} : { kind }), uuid: target.uuid }); await listQuery.refetch(); setMessage(completionWarning ? `Merged. ${completionWarning}` : "Merged into the selected target; the source UUID is now a permanent alias."); }
  async function deleted() { setDraft(blank(kind)); setParameters(coserOnly ? {} : { kind }); await listQuery.refetch(); setMessage("Entity deleted from the database and UUID permanently tombstoned; files were not removed."); }
  return <main className="manage-page"><header className="manage-heading"><div><p>PORTABLE UUID ENTITIES</p><h2>{coserOnly ? "Coser" : "Core entities"}</h2></div><button type="button" onClick={() => { setParameters(coserOnly ? {} : { kind }); setDraft(blank(kind)); setAliasText(""); }}>＋ New</button></header>{!coserOnly ? <nav className="task-filters">{kinds.map((value) => <button key={value} type="button" className={kind === value ? "is-active" : ""} onClick={() => setParameters({ kind: value })}>{value}</button>)}</nav> : null}{message ? <p className="manage-message">{message}</p> : null}
    <section className="entity-manage-layout"><aside className="entity-manage-list">{data?.items.map((item) => <button type="button" className={item.uuid === selected ? "is-active" : ""} key={item.uuid} onClick={() => setParameters({ ...(coserOnly ? {} : { kind }), uuid: item.uuid, page: String(page) })}><strong>{item.name}</strong><span>{item.aliases.join(" / ") || item.uuid}</span></button>)}{data && data.totalPages > 1 ? <nav className="manage-pagination"><button disabled={page <= 1} onClick={() => setParameters({ ...(coserOnly ? {} : { kind }), page: String(page - 1) })}>←</button><span>{page}/{data.totalPages}</span><button disabled={page >= data.totalPages} onClick={() => setParameters({ ...(coserOnly ? {} : { kind }), page: String(page + 1) })}>→</button></nav> : null}</aside>
      <div className="entity-editor">{kind === "COSER" && draft.uuid ? <nav className="editor-tabs">{["profile", "social", "galleries", "manifest"].map((tab) => <button type="button" key={tab} className={coserTab === tab ? "is-active" : ""} onClick={() => setCoserTab(tab)}>{tab}</button>)}</nav> : null}
        {kind !== "COSER" || coserTab === "profile" || !draft.uuid ? <><EntityForm draft={draft} aliasText={aliasText} setAliasText={setAliasText} setDraft={setDraft} submit={save} saving={createState.loading || updateState.loading} valid={entityValid} />{kind === "COSER" && draft.uuid ? <><ManageCoserAssetsPanel coser={draft} onUpdated={async () => { const result = await detailQuery.refetch(); if (result.data) setDraft(result.data.manageCoreEntity); await listQuery.refetch(); }} /><ManageCoserMetadataImport coser={draft} onUpdated={async () => { const result = await detailQuery.refetch(); if (result.data) setDraft(result.data.manageCoreEntity); await listQuery.refetch(); }} /></> : null}</> : null}
        {kind === "TAG" && draft.uuid ? <section className="manage-panel tag-parent-editor"><h3>Direct parent DAG</h3><p>A Tag may have multiple parents. The batch save checks every affected Tag revision and the database rejects cycles.</p><div className="manage-inline-toolbar"><span>{draft.parents.length} direct parents</span><button type="button" onClick={() => setDraft({ ...draft, parents: [...draft.parents, { uuid: "", name: "", metadataRevision: 0 }] })}>Add parent</button></div>{draft.parents.map((parent, index) => <div className="manage-tag-row" key={`${parent.uuid}-${index}`}><ManageEntitySelector kind="TAG" label="Parent Tag" uuid={parent.uuid} name={parent.name} onSelect={(entity) => setDraft({ ...draft, parents: draft.parents.map((value, position) => position === index ? { uuid: entity.uuid, name: entity.name, metadataRevision: entity.metadataRevision } : value) })} /><button type="button" onClick={() => setDraft({ ...draft, parents: draft.parents.filter((_, position) => position !== index) })}>Remove</button></div>)}<div className="manage-panel-actions"><button type="button" disabled={replaceTagParentsState.loading || draft.parents.some((parent) => !parent.uuid)} onClick={saveTagParents}>{replaceTagParentsState.loading ? "Saving…" : "Save parent DAG"}</button></div></section> : null}
        {draft.uuid && (kind !== "COSER" || coserTab === "profile") ? <ManageEntityLifecyclePanel source={draft} onMerged={merged} onDeleted={deleted} /> : null}
        {kind === "COSER" && coserTab === "social" ? <section className="manage-panel"><h3>Social accounts</h3><div className="social-manage-list">{draft.socialAccounts.map((item) => <div key={item.uuid}><strong>{item.label || item.platformKey}</strong><span>{item.handle} · {item.status}</span><a href={item.url} target="_blank" rel="noreferrer">{item.url}</a></div>)}</div><form className="rule-form" onSubmit={addAccount}><label>Platform key<input required list="social-platform-keys" maxLength={64} pattern="[a-z0-9][a-z0-9_-]{0,63}" value={account.platformKey} onChange={(event) => setAccount({ ...account, platformKey: event.target.value })} /><small>Choose a common platform or type a custom lowercase key.</small></label><datalist id="social-platform-keys">{socialPlatformOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</datalist><label>Label<input maxLength={100} value={account.label} onChange={(event) => setAccount({ ...account, label: event.target.value })} /></label><label>Handle<input maxLength={200} value={account.handle} onChange={(event) => setAccount({ ...account, handle: event.target.value })} /></label><label>HTTP(S) URL<input type="url" required value={account.url} onChange={(event) => setAccount({ ...account, url: event.target.value })} /></label><label>Status<select value={account.status} onChange={(event) => setAccount({ ...account, status: event.target.value })}><option>ACTIVE</option><option>INACTIVE</option></select></label><label className="check"><input type="checkbox" checked={account.visible} onChange={(event) => setAccount({ ...account, visible: event.target.checked })} /> Visible</label><button type="submit" disabled={!socialAccountValid || addSocialState.loading}>{addSocialState.loading ? "Adding…" : "Add account"}</button></form></section> : null}
        {kind === "COSER" && coserTab === "galleries" ? <section className="manage-panel"><h3>Associated galleries</h3><p>Gallery relations are edited from each Gallery aggregate.</p><Link to={`/coser/${draft.slug}`}>Open unified Coser detail</Link></section> : null}
        {kind === "COSER" && coserTab === "manifest" ? <section className="manage-panel manage-manifest"><h3>Coser Manifest</h3><p>The independent Coser profile snapshot is optional and stored below the single configured metadata root. Pull and Push are always explicit.</p>
          {manifestQuery.loading ? <p>Checking Manifest…</p> : manifestQuery.error ? <p className="manage-error">Manifest inspection failed: {manifestQuery.error.message}</p> : manifestQuery.data ? <><dl><dt>Status</dt><dd><strong className={`manifest-status is-${manifestQuery.data.manageCoserManifest.status.toLowerCase()}`}>{manifestQuery.data.manageCoserManifest.status}</strong></dd><dt>Path</dt><dd>{manifestQuery.data.manageCoserManifest.path}</dd><dt>Manifest revision</dt><dd>{manifestQuery.data.manageCoserManifest.manifestRevision}</dd><dt>Database revision</dt><dd>{manifestQuery.data.manageCoserManifest.metadataRevision}</dd></dl>
            {manifestQuery.data.manageCoserManifest.conflicts.length ? <div className="manifest-conflicts"><h4>Conflicts require an explicit decision for every field</h4>{manifestQuery.data.manageCoserManifest.conflicts.map((conflict) => <article key={conflict.path}><code>{conflict.path}</code><div><label>Database<pre>{conflict.databaseJSON}</pre></label><label>Manifest file<pre>{conflict.fileJSON}</pre></label></div><select aria-label={`Resolution for ${conflict.path}`} value={conflictChoices[conflict.path] || ""} onChange={(event) => setConflictChoices({ ...conflictChoices, [conflict.path]: event.target.value as "DATABASE" | "FILE" })}><option value="">Choose…</option><option value="DATABASE">Keep database</option><option value="FILE">Use Manifest file</option></select></article>)}<button type="button" disabled={resolveManifestState.loading} onClick={resolveCoserManifest}>{resolveManifestState.loading ? "Resolving…" : "Resolve all and Pull"}</button></div> : null}</> : null}
          <div className="manage-panel-actions"><button type="button" onClick={() => manifestQuery.refetch()}>Check again</button><button type="button" disabled={pushManifestState.loading} onClick={() => runCoserManifest("PUSH")}>{pushManifestState.loading ? "Pushing…" : "Push database → Manifest"}</button><button type="button" disabled={pullManifestState.loading} onClick={() => runCoserManifest("PULL")}>{pullManifestState.loading ? "Pulling…" : "Pull Manifest → database"}</button></div>
        </section> : null}</div></section></main>;
}

function EntityForm({ draft, aliasText, setAliasText, setDraft, submit, saving, valid }: { draft: ManageCoreEntity; aliasText: string; setAliasText: (value: string) => void; setDraft: (value: ManageCoreEntity) => void; submit: (event: FormEvent) => void; saving: boolean; valid: boolean }) {
  return <form className="metadata-form" onSubmit={submit}><label>Name (required)<input required maxLength={300} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Sort name<input maxLength={300} value={draft.sortName} onChange={(event) => setDraft({ ...draft, sortName: event.target.value })} /></label><label className="span-2">Aliases<input aria-describedby="entity-aliases-help" value={aliasText} onChange={(event) => setAliasText(event.target.value)} /><small id="entity-aliases-help">Separate multiple aliases with /, for example: Komachi / こまち / 小丁.</small></label>{draft.kind === "CHARACTER" ? <div className="span-2 required-entity-field"><strong>Primary Work (required)</strong><ManageEntitySelector kind="WORK" label="Primary Work" uuid={draft.workUUID || ""} name="" onSelect={(entity) => setDraft({ ...draft, workUUID: entity.uuid })} />{!draft.workUUID ? <small>Select an existing Work before creating the Character.</small> : null}</div> : null}{draft.kind === "TAG" ? <label className="span-2 settings-check"><input type="checkbox" checked={draft.useInRecommendation} onChange={(event) => setDraft({ ...draft, useInRecommendation: event.target.checked })} /> Use in recommendations</label> : null}{draft.kind === "COSER" ? <><label className="span-2">Profile summary<textarea maxLength={20000} value={draft.profileSummary} onChange={(event) => setDraft({ ...draft, profileSummary: event.target.value })} /></label><label className="span-2">Biography (restricted Markdown)<textarea maxLength={20000} value={draft.biography} onChange={(event) => setDraft({ ...draft, biography: event.target.value })} /></label><label>Country / region<input maxLength={100} value={draft.countryOrRegion} onChange={(event) => setDraft({ ...draft, countryOrRegion: event.target.value })} /></label></> : null}<footer className="span-2"><button type="submit" disabled={!valid || saving}>{saving ? "Saving…" : draft.uuid ? `Save revision ${draft.metadataRevision}` : "Create"}</button></footer></form>;
}
