package productdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"sort"
	"time"

	"github.com/stashapp/stash/internal/coversimilarity"
	"github.com/stashapp/stash/internal/gallery"
	"github.com/stashapp/stash/internal/mediaprocessing"
)

type CoverSimilarityStore struct{ db *sql.DB }

func (db *Database) CoverSimilarity() *CoverSimilarityStore { return &CoverSimilarityStore{db: db.DB} }

type CoverSignatureArtifact struct {
	ItemUUID          string
	ContentRevision   int64
	ProfileHash       string
	CacheRelativePath string
}

func (s *CoverSimilarityStore) NextUnhashed(ctx context.Context) (CoverSignatureArtifact, error) {
	var result CoverSignatureArtifact
	err := s.db.QueryRowContext(ctx, `SELECT d.item_uuid,d.content_revision,d.profile_hash,d.cache_relative_path
		FROM media_derivatives d JOIN gallery_items i ON i.item_uuid=d.item_uuid
		LEFT JOIN cover_image_signatures h ON h.item_uuid=d.item_uuid AND h.content_revision=d.content_revision
			AND h.profile_hash=d.profile_hash AND h.signature_version=?
		LEFT JOIN cover_signature_backfill_attempts a ON a.item_uuid=d.item_uuid AND a.content_revision=d.content_revision
			AND a.profile_hash=d.profile_hash
		WHERE d.variant=? AND d.is_current=1 AND d.state='READY' AND i.media_kind='STATIC_IMAGE'
			AND i.content_revision=d.content_revision AND i.availability_state='AVAILABLE' AND h.item_uuid IS NULL
			AND (a.attempted_at_utc IS NULL OR a.attempted_at_utc<?)
		ORDER BY CASE WHEN EXISTS(SELECT 1 FROM gallery_covers c WHERE c.gallery_id=i.gallery_id
			AND c.preferred_item_uuid=i.item_uuid) THEN 0 ELSE 1 END,d.id LIMIT 1`,
		coversimilarity.Version, mediaprocessing.VariantCard480,
		formatTime(normalisedTime(time.Now().Add(-time.Hour)))).Scan(&result.ItemUUID, &result.ContentRevision, &result.ProfileHash, &result.CacheRelativePath)
	return result, err
}

func (s *CoverSimilarityStore) RecordBackfillFailure(ctx context.Context, artifact CoverSignatureArtifact, now time.Time) error {
	_, err := s.db.ExecContext(ctx, `INSERT INTO cover_signature_backfill_attempts
		(item_uuid,content_revision,profile_hash,attempted_at_utc) VALUES(?,?,?,?)
		ON CONFLICT(item_uuid,content_revision,profile_hash) DO UPDATE SET attempted_at_utc=excluded.attempted_at_utc`,
		artifact.ItemUUID, artifact.ContentRevision, artifact.ProfileHash, formatTime(normalisedTime(now)))
	return err
}

// SaveSignature may be called again after a crash. Stale generated bytes can
// never overwrite a current item's signature.
func (s *CoverSimilarityStore) SaveSignature(ctx context.Context, artifact CoverSignatureArtifact, signature coversimilarity.Signature, now time.Time) error {
	if artifact.ItemUUID == "" || artifact.ContentRevision <= 0 || artifact.ProfileHash == "" || signature.Width <= 0 || signature.Height <= 0 {
		return errors.New("invalid cover signature")
	}
	_, err := s.db.ExecContext(ctx, `INSERT INTO cover_image_signatures
		(item_uuid,content_revision,profile_hash,signature_version,dhash_h,dhash_v,phash,width,height,created_at_utc)
		SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM gallery_items i JOIN media_derivatives d
			ON d.item_uuid=i.item_uuid AND d.content_revision=i.content_revision
			WHERE i.item_uuid=? AND i.content_revision=? AND d.variant=? AND d.profile_hash=?
			AND d.is_current=1 AND d.state='READY' AND d.cache_relative_path=?)
		ON CONFLICT(item_uuid,content_revision,profile_hash,signature_version) DO NOTHING`,
		artifact.ItemUUID, artifact.ContentRevision, artifact.ProfileHash, coversimilarity.Version,
		coversimilarity.Hex(signature.DHashH), coversimilarity.Hex(signature.DHashV), coversimilarity.Hex(signature.PHash),
		signature.Width, signature.Height, formatTime(normalisedTime(now)), artifact.ItemUUID, artifact.ContentRevision,
		mediaprocessing.VariantCard480, artifact.ProfileHash, artifact.CacheRelativePath)
	if err != nil {
		return err
	}
	// Old signatures needed by a pending decision are already copied into its
	// durable intent during the scan transaction; do not retain every prior
	// content revision indefinitely.
	_, err = s.db.ExecContext(ctx, `DELETE FROM cover_image_signatures WHERE item_uuid=? AND content_revision<>?
		AND EXISTS(SELECT 1 FROM gallery_items WHERE item_uuid=? AND content_revision=?)`,
		artifact.ItemUUID, artifact.ContentRevision, artifact.ItemUUID, artifact.ContentRevision)
	return err
}

func loadCoverSignature(ctx context.Context, tx *sql.Tx, itemUUID string, revision int64) (coversimilarity.Signature, bool, error) {
	var h, v, p string
	var result coversimilarity.Signature
	err := tx.QueryRowContext(ctx, `SELECT s.dhash_h,s.dhash_v,s.phash,s.width,s.height
		FROM cover_image_signatures s WHERE s.item_uuid=? AND s.content_revision=? AND s.signature_version=?
		ORDER BY s.created_at_utc DESC LIMIT 1`, itemUUID, revision, coversimilarity.Version).Scan(&h, &v, &p, &result.Width, &result.Height)
	if errors.Is(err, sql.ErrNoRows) {
		return result, false, nil
	}
	if err != nil {
		return result, false, err
	}
	if result.DHashH, err = coversimilarity.ParseHex(h); err != nil {
		return result, false, err
	}
	if result.DHashV, err = coversimilarity.ParseHex(v); err != nil {
		return result, false, err
	}
	if result.PHash, err = coversimilarity.ParseHex(p); err != nil {
		return result, false, err
	}
	return result, true, nil
}

type coverCandidate struct {
	UUID     string `json:"uuid"`
	Revision int64  `json:"revision"`
}

func stageCoverSimilarityIntent(ctx context.Context, tx *sql.Tx, galleryID, scanRunID int64, old *coversimilarity.Signature, candidates []string, now time.Time) error {
	if len(candidates) == 0 {
		return nil
	}
	seen := make(map[string]bool, len(candidates))
	list := make([]coverCandidate, 0, len(candidates))
	for _, uuid := range candidates {
		if seen[uuid] {
			continue
		}
		seen[uuid] = true
		var revision int64
		var excluded int
		var kind gallery.MediaKind
		if err := tx.QueryRowContext(ctx, `SELECT content_revision,excluded,media_kind FROM gallery_items
			WHERE item_uuid=? AND gallery_id=? AND availability_state='AVAILABLE'`, uuid, galleryID).Scan(&revision, &excluded, &kind); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
		if excluded == 0 && kind == gallery.MediaKindStaticImage {
			list = append(list, coverCandidate{UUID: uuid, Revision: revision})
		}
	}
	if len(list) == 0 {
		return nil
	}
	sort.Slice(list, func(i, j int) bool { return list[i].UUID < list[j].UUID })
	oldJSON, err := json.Marshal(old)
	if err != nil {
		return err
	}
	candidatesJSON, err := json.Marshal(list)
	if err != nil {
		return err
	}
	var coverRevision, metadataRevision int64
	if err := tx.QueryRowContext(ctx, `SELECT c.cover_revision,g.metadata_revision FROM gallery_covers c
		JOIN galleries g ON g.id=c.gallery_id WHERE c.gallery_id=?`, galleryID).Scan(&coverRevision, &metadataRevision); err != nil {
		return err
	}
	status := "PENDING"
	var completed any
	if old == nil {
		status = "NO_SIGNATURE"
		completed = formatTime(normalisedTime(now))
	}
	_, err = tx.ExecContext(ctx, `INSERT INTO cover_similarity_intents
		(gallery_id,scan_run_id,old_signature_json,candidates_json,expected_cover_revision,expected_metadata_revision,status,created_at_utc,next_check_at_utc,completed_at_utc)
		VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(scan_run_id) DO UPDATE SET
		scan_run_id=excluded.scan_run_id,old_signature_json=excluded.old_signature_json,
		candidates_json=excluded.candidates_json,expected_cover_revision=excluded.expected_cover_revision,
		expected_metadata_revision=excluded.expected_metadata_revision,status=excluded.status,qualified_count=0,
		selected_item_uuid=NULL,created_at_utc=excluded.created_at_utc,next_check_at_utc=excluded.next_check_at_utc,completed_at_utc=excluded.completed_at_utc`,
		galleryID, scanRunID, oldJSON, candidatesJSON, coverRevision, metadataRevision,
		status, formatTime(normalisedTime(now)), formatTime(normalisedTime(now)), completed)
	return err
}

// ResolveOne evaluates at most one durable intent. An unfinished candidate
// job leaves it pending; retries and process restarts are safe.
func (s *CoverSimilarityStore) ResolveOne(ctx context.Context, now time.Time) (bool, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return false, err
	}
	defer func() { _ = tx.Rollback() }()
	var galleryID, scanRunID, coverRevision, metadataRevision int64
	var oldJSON, candidatesJSON []byte
	var createdAt string
	err = tx.QueryRowContext(ctx, `SELECT gallery_id,scan_run_id,old_signature_json,candidates_json,
		expected_cover_revision,expected_metadata_revision,created_at_utc FROM cover_similarity_intents
		WHERE status='PENDING' AND next_check_at_utc<=? ORDER BY next_check_at_utc,scan_run_id LIMIT 1`,
		formatTime(normalisedTime(now))).Scan(&galleryID, &scanRunID, &oldJSON, &candidatesJSON, &coverRevision, &metadataRevision, &createdAt)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	finish := func(status, selected string, qualified int) (bool, error) {
		_, err := tx.ExecContext(ctx, `UPDATE cover_similarity_intents SET status=?,qualified_count=?,selected_item_uuid=NULLIF(?,''),completed_at_utc=?
			WHERE gallery_id=? AND scan_run_id=? AND status='PENDING'`, status, qualified, selected,
			formatTime(normalisedTime(now)), galleryID, scanRunID)
		if err != nil {
			return false, err
		}
		return true, tx.Commit()
	}
	created, err := parseTime(createdAt)
	if err != nil || now.After(created.Add(24*time.Hour)) {
		return finish("FALLBACK", "", 0)
	}
	var currentCover, currentMetadata int64
	var preferred string
	err = tx.QueryRowContext(ctx, `SELECT c.cover_revision,g.metadata_revision,c.preferred_kind
		FROM galleries g JOIN gallery_covers c ON c.gallery_id=g.id WHERE g.id=?`, galleryID).
		Scan(&currentCover, &currentMetadata, &preferred)
	if errors.Is(err, sql.ErrNoRows) {
		return finish("STALE", "", 0)
	}
	if err != nil {
		return false, err
	}
	var runStatus string
	if err := tx.QueryRowContext(ctx, `SELECT status FROM gallery_scan_runs WHERE id=?`, scanRunID).Scan(&runStatus); err != nil {
		return false, err
	}
	var latestScan int64
	if err := tx.QueryRowContext(ctx, `SELECT MAX(id) FROM gallery_scan_runs WHERE source_id IN
		(SELECT id FROM gallery_sources WHERE gallery_id=?)`, galleryID).Scan(&latestScan); err != nil {
		return false, err
	}
	if currentCover != coverRevision || currentMetadata != metadataRevision || preferred != string(gallery.CoverAutoRandom) || runStatus != "COMPLETED" || latestScan != scanRunID {
		return finish("STALE", "", 0)
	}
	var old coversimilarity.Signature
	var candidates []coverCandidate
	if err := json.Unmarshal(oldJSON, &old); err != nil {
		return finish("NO_SIGNATURE", "", 0)
	}
	if err := json.Unmarshal(candidatesJSON, &candidates); err != nil {
		return finish("FALLBACK", "", 0)
	}
	var available []coversimilarity.Candidate
	for _, candidate := range candidates {
		var currentRevision int64
		var excluded int
		var availability string
		if err := tx.QueryRowContext(ctx, `SELECT content_revision,excluded,availability_state FROM gallery_items
			WHERE item_uuid=? AND gallery_id=?`, candidate.UUID, galleryID).Scan(&currentRevision, &excluded, &availability); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return false, err
		}
		if currentRevision != candidate.Revision || excluded != 0 || availability != "AVAILABLE" {
			continue
		}
		displayable, err := isStaticCoverAvailable(ctx, tx, galleryID, candidate.UUID)
		if err != nil {
			return false, err
		}
		sig, found, err := loadCoverSignature(ctx, tx, candidate.UUID, candidate.Revision)
		if err != nil {
			return false, err
		}
		if !found || !displayable {
			var active int
			if err := tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM processing_jobs WHERE item_uuid=? AND variant=?
				AND content_revision=? AND status IN ('PENDING','RUNNING','RETRY_WAIT','PAUSED')`,
				candidate.UUID, mediaprocessing.VariantCard480, candidate.Revision).Scan(&active); err != nil {
				return false, err
			}
			if active > 0 {
				if _, err := tx.ExecContext(ctx, `UPDATE cover_similarity_intents SET next_check_at_utc=?
					WHERE scan_run_id=? AND status='PENDING'`, formatTime(normalisedTime(now.Add(5*time.Second))), scanRunID); err != nil {
					return false, err
				}
				return true, tx.Commit()
			}
			continue
		}
		available = append(available, coversimilarity.Candidate{ID: candidate.UUID, Signature: sig})
	}
	selected, qualified := coversimilarity.Select(old, available)
	if selected == "" {
		return finish("NO_MATCH", "", 0)
	}
	state, _, err := findCover(ctx, tx, galleryID)
	if err != nil {
		return false, err
	}
	state.PreferredKind, state.PreferredItemUUID = gallery.CoverItem, selected
	state.Revision++
	state.CanUndo = false
	state.UpdatedAtUTC = normalisedTime(now)
	if err := recomputeEffectiveCover(ctx, tx, &state, false, nil, now); err != nil {
		return false, err
	}
	if err := persistCoverClearingPrevious(ctx, tx, state); err != nil {
		return false, err
	}
	if err := touchGalleryCoverMetadata(ctx, tx, galleryID, &metadataRevision, now); err != nil {
		return false, err
	}
	status := "MATCHED"
	if qualified > 1 {
		status = "MULTIPLE_MATCHED"
	}
	return finish(status, selected, qualified)
}
