// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package productapi

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type BrowseGalleryCard struct {
	SetID              string             `json:"setID"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	CollectionType     CollectionType     `json:"collectionType"`
	ContentRating      ContentRating      `json:"contentRating"`
	Cover              *GalleryCover      `json:"cover"`
	Credits            []*PersonSummary   `json:"credits"`
	CreditCount        int                `json:"creditCount"`
	Characters         []*EntitySummary   `json:"characters"`
	CharacterCount     int                `json:"characterCount"`
	Works              []*EntitySummary   `json:"works"`
	WorkCount          int                `json:"workCount"`
	ShootDate          string             `json:"shootDate"`
	ShootDatePrecision ShootDatePrecision `json:"shootDatePrecision"`
	AddedAtUtc         string             `json:"addedAtUTC"`
	Media              *MediaCounts       `json:"media"`
	Favorite           bool               `json:"favorite"`
	RatingHalfSteps    *int               `json:"ratingHalfSteps,omitempty"`
	ScrubberCount      int                `json:"scrubberCount"`
	ScrubberRevision   int64              `json:"scrubberRevision"`
}

type BrowseUISettings struct {
	SettingsRevision              int64 `json:"settingsRevision"`
	GalleryScrubberEnabled        bool  `json:"galleryScrubberEnabled"`
	DetailMediaFilterEnabled      bool  `json:"detailMediaFilterEnabled"`
	GalleryAnimatedPlaybackLimit  int   `json:"galleryAnimatedPlaybackLimit"`
	GalleryAnimatedLockIntervalMs int   `json:"galleryAnimatedLockIntervalMS"`
	CardFavoriteControlVisible    bool  `json:"cardFavoriteControlVisible"`
	CardRatingSummaryVisible      bool  `json:"cardRatingSummaryVisible"`
	DetailRatingControlVisible    bool  `json:"detailRatingControlVisible"`
}

type CharacterDetail struct {
	Entity     *EntityIndexItem `json:"entity"`
	Work       *EntityIndexItem `json:"work"`
	Galleries  *GalleryPage     `json:"galleries"`
	Redirected bool             `json:"redirected"`
}

type CoreEntityInput struct {
	Kind                SearchEntityKind `json:"kind"`
	Name                string           `json:"name"`
	SortName            string           `json:"sortName"`
	Aliases             []string         `json:"aliases"`
	WorkUUID            *string          `json:"workUUID,omitempty"`
	ProfileSummary      string           `json:"profileSummary"`
	Biography           string           `json:"biography"`
	CountryOrRegion     string           `json:"countryOrRegion"`
	UseInRecommendation bool             `json:"useInRecommendation"`
}

type CoserDetail struct {
	Entity          *EntityIndexItem `json:"entity"`
	ProfileSummary  string           `json:"profileSummary"`
	Biography       string           `json:"biography"`
	CountryOrRegion string           `json:"countryOrRegion"`
	SocialAccounts  []*SocialAccount `json:"socialAccounts"`
	BannerURL       *string          `json:"bannerURL,omitempty"`
	Galleries       *GalleryPage     `json:"galleries"`
	Redirected      bool             `json:"redirected"`
}

type CreateMediaLibraryInput struct {
	Name            string `json:"name"`
	RootPath        string `json:"rootPath"`
	Enabled         bool   `json:"enabled"`
	ReadOnly        bool   `json:"readOnly"`
	CaptureTimezone string `json:"captureTimezone"`
}

type CreateRecognitionRuleInput struct {
	LibraryID       int64  `json:"libraryID"`
	Name            string `json:"name"`
	Kind            string `json:"kind"`
	Enabled         bool   `json:"enabled"`
	AutoCreateDraft bool   `json:"autoCreateDraft"`
	Order           int    `json:"order"`
	Pattern         string `json:"pattern"`
	FixedDepth      int    `json:"fixedDepth"`
}

type EntityIndexItem struct {
	Kind      SearchEntityKind `json:"kind"`
	UUID      string           `json:"uuid"`
	Slug      string           `json:"slug"`
	Name      string           `json:"name"`
	Aliases   []string         `json:"aliases"`
	AvatarURL *string          `json:"avatarURL,omitempty"`
}

type EntityPage struct {
	Items      []*EntityIndexItem `json:"items"`
	Page       int                `json:"page"`
	PageSize   int                `json:"pageSize"`
	TotalItems int                `json:"totalItems"`
	TotalPages int                `json:"totalPages"`
}

type EntitySummary struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}

type ExpectedTagRevisionInput struct {
	UUID             string `json:"uuid"`
	MetadataRevision int64  `json:"metadataRevision"`
}

type ExternalLink struct {
	UUID  string `json:"uuid"`
	Type  string `json:"type"`
	Label string `json:"label"`
	URL   string `json:"url"`
}

type GalleryCover struct {
	Kind     string            `json:"kind"`
	Revision int64             `json:"revision"`
	Managed  bool              `json:"managed"`
	Warning  bool              `json:"warning"`
	Resource *ResourceIdentity `json:"resource,omitempty"`
}

type GalleryCreditDetail struct {
	Coser      *PersonSummary   `json:"coser"`
	Characters []*EntitySummary `json:"characters"`
	Works      []*EntitySummary `json:"works"`
}

type GalleryDetail struct {
	Card                   *BrowseGalleryCard     `json:"card"`
	Description            string                 `json:"description"`
	PhotographerName       string                 `json:"photographerName"`
	StudioName             string                 `json:"studioName"`
	AvailableBytes         int64                  `json:"availableBytes"`
	MediaParentDirectories []string               `json:"mediaParentDirectories"`
	Credits                []*GalleryCreditDetail `json:"credits"`
	Tags                   []*EntitySummary       `json:"tags"`
	ExternalLinks          []*ExternalLink        `json:"externalLinks"`
	Redirected             bool                   `json:"redirected"`
}

type GalleryExternalLinkInput struct {
	Type     string `json:"type"`
	Label    string `json:"label"`
	URL      string `json:"url"`
	Position string `json:"position"`
}

type GalleryMember struct {
	ItemUUID        string            `json:"itemUUID"`
	MediaKind       MediaKind         `json:"mediaKind"`
	ContentFormat   ContentFormat     `json:"contentFormat"`
	ImageCategory   *ImageCategory    `json:"imageCategory,omitempty"`
	Position        string            `json:"position"`
	Caption         string            `json:"caption"`
	ProcessingState ProcessingState   `json:"processingState"`
	CardResource    *ResourceIdentity `json:"cardResource,omitempty"`
	LargeResource   *ResourceIdentity `json:"largeResource,omitempty"`
	Favorite        bool              `json:"favorite"`
	RatingHalfSteps *int              `json:"ratingHalfSteps,omitempty"`
}

type GalleryMemberIndex struct {
	SetID            string           `json:"setID"`
	MetadataRevision int64            `json:"metadataRevision"`
	ScanRevision     int64            `json:"scanRevision"`
	Items            []*GalleryMember `json:"items"`
}

type GalleryPage struct {
	Items      []*BrowseGalleryCard `json:"items"`
	Page       int                  `json:"page"`
	PageSize   int                  `json:"pageSize"`
	TotalItems int                  `json:"totalItems"`
	TotalPages int                  `json:"totalPages"`
}

type GalleryRecommendation struct {
	Card    *BrowseGalleryCard `json:"card"`
	Score   float64            `json:"score"`
	Reasons []string           `json:"reasons"`
}

type HomeGalleryPage struct {
	Scope BrowseScope  `json:"scope"`
	Page  *GalleryPage `json:"page"`
}

type ManageAuditEvent struct {
	ID          int64  `json:"id"`
	EventCode   string `json:"eventCode"`
	TargetKind  string `json:"targetKind"`
	TargetID    string `json:"targetID"`
	Outcome     string `json:"outcome"`
	ErrorCode   string `json:"errorCode"`
	SummaryJSON string `json:"summaryJSON"`
	CreatedAt   string `json:"createdAt"`
}

type ManageAuditPage struct {
	Items      []*ManageAuditEvent `json:"items"`
	Page       int                 `json:"page"`
	PageSize   int                 `json:"pageSize"`
	TotalItems int                 `json:"totalItems"`
	TotalPages int                 `json:"totalPages"`
}

type ManageAvatarCrop struct {
	X    float64 `json:"x"`
	Y    float64 `json:"y"`
	Size float64 `json:"size"`
}

type ManageBackupRecord struct {
	ID                     string  `json:"id"`
	Kind                   string  `json:"kind"`
	FileName               string  `json:"fileName"`
	Status                 string  `json:"status"`
	ByteSize               int64   `json:"byteSize"`
	ArchiveSha256          string  `json:"archiveSHA256"`
	ProductVersion         string  `json:"productVersion"`
	DatabaseSchemaVersion  int     `json:"databaseSchemaVersion"`
	ManifestSchemaVersion  int     `json:"manifestSchemaVersion"`
	MediaProcessingVersion int     `json:"mediaProcessingVersion"`
	CreatedAt              string  `json:"createdAt"`
	CompletedAt            *string `json:"completedAt,omitempty"`
	LastErrorCode          string  `json:"lastErrorCode"`
}

type ManageCacheStorage struct {
	Path             string `json:"path"`
	ByteSize         int64  `json:"byteSize"`
	FileCount        int64  `json:"fileCount"`
	BaseByteSize     int64  `json:"baseByteSize"`
	EnhancedByteSize int64  `json:"enhancedByteSize"`
}

type ManageCandidate struct {
	ID              int64               `json:"id"`
	RootPath        string              `json:"rootPath"`
	SourceType      string              `json:"sourceType"`
	Method          string              `json:"method"`
	ManifestSetID   *string             `json:"manifestSetID,omitempty"`
	Status          string              `json:"status"`
	AutoCreateDraft bool                `json:"autoCreateDraft"`
	HasConflict     bool                `json:"hasConflict"`
	OverLimit       bool                `json:"overLimit"`
	MediaCount      int                 `json:"mediaCount"`
	Suggestions     []*ManageSuggestion `json:"suggestions"`
}

type ManageCoreEntity struct {
	Kind                SearchEntityKind       `json:"kind"`
	UUID                string                 `json:"uuid"`
	Name                string                 `json:"name"`
	SortName            string                 `json:"sortName"`
	Aliases             []string               `json:"aliases"`
	Slug                string                 `json:"slug"`
	MetadataRevision    int64                  `json:"metadataRevision"`
	WorkUUID            *string                `json:"workUUID,omitempty"`
	ProfileSummary      string                 `json:"profileSummary"`
	Biography           string                 `json:"biography"`
	CountryOrRegion     string                 `json:"countryOrRegion"`
	UseInRecommendation bool                   `json:"useInRecommendation"`
	AvatarURL           *string                `json:"avatarURL,omitempty"`
	BannerURL           *string                `json:"bannerURL,omitempty"`
	AvatarCrop          *ManageAvatarCrop      `json:"avatarCrop,omitempty"`
	BannerFocalPoint    *ManageFocalPoint      `json:"bannerFocalPoint,omitempty"`
	SocialAccounts      []*ManageSocialAccount `json:"socialAccounts"`
	Parents             []*ManageCoreEntityRef `json:"parents"`
}

type ManageCoreEntityDeleteBlocker struct {
	Code           string `json:"code"`
	ReferenceCount int64  `json:"referenceCount"`
}

type ManageCoreEntityDeletePreview struct {
	Kind             SearchEntityKind                 `json:"kind"`
	UUID             string                           `json:"uuid"`
	MetadataRevision int64                            `json:"metadataRevision"`
	ReferenceCount   int64                            `json:"referenceCount"`
	Blockers         []*ManageCoreEntityDeleteBlocker `json:"blockers"`
	CanDelete        bool                             `json:"canDelete"`
}

type ManageCoreEntityMergeConflict struct {
	Code    string `json:"code"`
	Details string `json:"details"`
}

type ManageCoreEntityMergePreview struct {
	Kind               SearchEntityKind                 `json:"kind"`
	SourceUUID         string                           `json:"sourceUUID"`
	TargetUUID         string                           `json:"targetUUID"`
	SourceRevision     int64                            `json:"sourceRevision"`
	TargetRevision     int64                            `json:"targetRevision"`
	AffectedGalleryIDs []int64                          `json:"affectedGalleryIDs"`
	Conflicts          []*ManageCoreEntityMergeConflict `json:"conflicts"`
	CanMerge           bool                             `json:"canMerge"`
}

type ManageCoreEntityMergeResult struct {
	Target            *ManageCoreEntity             `json:"target"`
	Preview           *ManageCoreEntityMergePreview `json:"preview"`
	CompletionWarning *string                       `json:"completionWarning,omitempty"`
}

type ManageCoreEntityPage struct {
	Items      []*ManageCoreEntity `json:"items"`
	Page       int                 `json:"page"`
	PageSize   int                 `json:"pageSize"`
	TotalItems int                 `json:"totalItems"`
	TotalPages int                 `json:"totalPages"`
}

type ManageCoreEntityRef struct {
	UUID             string `json:"uuid"`
	Name             string `json:"name"`
	MetadataRevision int64  `json:"metadataRevision"`
}

type ManageCoserManifestState struct {
	Status           string                    `json:"status"`
	Path             string                    `json:"path"`
	ManifestRevision int                       `json:"manifestRevision"`
	MetadataRevision int64                     `json:"metadataRevision"`
	Conflicts        []*ManageManifestConflict `json:"conflicts"`
}

type ManageDiscoverySnapshot struct {
	ID          int64                         `json:"id"`
	LibraryID   int64                         `json:"libraryID"`
	CompletedAt string                        `json:"completedAt"`
	Candidates  []*ManageCandidate            `json:"candidates"`
	Unassigned  []*ManageUnassignedDiagnostic `json:"unassigned"`
}

type ManageFocalPoint struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type ManageGalleryCast struct {
	CharacterUUID string `json:"characterUUID"`
	CharacterName string `json:"characterName"`
	WorkUUID      string `json:"workUUID"`
	WorkName      string `json:"workName"`
	Position      string `json:"position"`
}

type ManageGalleryCredit struct {
	CoserUUID string               `json:"coserUUID"`
	CoserName string               `json:"coserName"`
	Position  string               `json:"position"`
	Cast      []*ManageGalleryCast `json:"cast"`
}

type ManageGalleryDeletePreview struct {
	SetID                      string       `json:"setID"`
	State                      GalleryState `json:"state"`
	MetadataRevision           int64        `json:"metadataRevision"`
	ItemCount                  int64        `json:"itemCount"`
	ExternalLinkCount          int64        `json:"externalLinkCount"`
	ExecutableJobCount         int64        `json:"executableJobCount"`
	IgnoredSourceWillBeCreated bool         `json:"ignoredSourceWillBeCreated"`
	CanDelete                  bool         `json:"canDelete"`
}

type ManageGalleryDetail struct {
	Row                *ManageGalleryRow            `json:"row"`
	Aliases            []string                     `json:"aliases"`
	Description        string                       `json:"description"`
	ShootDate          string                       `json:"shootDate"`
	ShootDatePrecision ShootDatePrecision           `json:"shootDatePrecision"`
	PhotographerName   string                       `json:"photographerName"`
	StudioName         string                       `json:"studioName"`
	Items              []*ManageGalleryItem         `json:"items"`
	Credits            []*ManageGalleryCredit       `json:"credits"`
	Tags               []*ManageGalleryTag          `json:"tags"`
	ExternalLinks      []*ManageGalleryExternalLink `json:"externalLinks"`
	FolderMatches      []*ManageGalleryFolderMatch  `json:"folderMatches"`
}

type ManageGalleryExternalLink struct {
	UUID     string `json:"uuid"`
	Type     string `json:"type"`
	Label    string `json:"label"`
	URL      string `json:"url"`
	Position string `json:"position"`
}

type ManageGalleryFolderMatch struct {
	Kind        SearchEntityKind `json:"kind"`
	UUID        string           `json:"uuid"`
	Name        string           `json:"name"`
	MatchedName string           `json:"matchedName"`
	WorkUUID    string           `json:"workUUID"`
	WorkName    string           `json:"workName"`
}

type ManageGalleryItem struct {
	UUID                 string          `json:"uuid"`
	RelativePath         string          `json:"relativePath"`
	MediaKind            MediaKind       `json:"mediaKind"`
	ContentFormat        ContentFormat   `json:"contentFormat"`
	ImageCategory        *ImageCategory  `json:"imageCategory,omitempty"`
	Position             string          `json:"position"`
	Caption              string          `json:"caption"`
	Excluded             bool            `json:"excluded"`
	Availability         string          `json:"availability"`
	ProcessingState      ProcessingState `json:"processingState"`
	ByteSize             int64           `json:"byteSize"`
	VideoProbeState      string          `json:"videoProbeState"`
	VideoErrorCode       string          `json:"videoErrorCode"`
	VideoContainer       string          `json:"videoContainer"`
	VideoDurationSeconds float64         `json:"videoDurationSeconds"`
	VideoWidth           int             `json:"videoWidth"`
	VideoHeight          int             `json:"videoHeight"`
	VideoCodec           string          `json:"videoCodec"`
	AudioCodec           string          `json:"audioCodec"`
}

type ManageGalleryManifestState struct {
	Status           string                    `json:"status"`
	Path             string                    `json:"path"`
	ManifestRevision int                       `json:"manifestRevision"`
	MetadataRevision int64                     `json:"metadataRevision"`
	Conflicts        []*ManageManifestConflict `json:"conflicts"`
}

type ManageGalleryPage struct {
	Items      []*ManageGalleryRow `json:"items"`
	Summary    *ManageIssueSummary `json:"summary"`
	Page       int                 `json:"page"`
	PageSize   int                 `json:"pageSize"`
	TotalItems int                 `json:"totalItems"`
	TotalPages int                 `json:"totalPages"`
}

type ManageGalleryRow struct {
	SetID              string         `json:"setID"`
	Slug               string         `json:"slug"`
	State              GalleryState   `json:"state"`
	Title              string         `json:"title"`
	ContentRating      *ContentRating `json:"contentRating,omitempty"`
	MetadataRevision   int64          `json:"metadataRevision"`
	ScanRevision       int64          `json:"scanRevision"`
	Browsable          bool           `json:"browsable"`
	SourceType         string         `json:"sourceType"`
	SourcePath         string         `json:"sourcePath"`
	SourceAvailability string         `json:"sourceAvailability"`
	ReconcileState     string         `json:"reconcileState"`
	OverLimit          bool           `json:"overLimit"`
	ItemCount          int            `json:"itemCount"`
	MissingCount       int            `json:"missingCount"`
	PendingCount       int            `json:"pendingCount"`
	ErrorCount         int            `json:"errorCount"`
	BlockingIssues     int            `json:"blockingIssues"`
}

type ManageGalleryTag struct {
	UUID     string `json:"uuid"`
	Name     string `json:"name"`
	Position string `json:"position"`
}

type ManageIssueSummary struct {
	Draft       int `json:"draft"`
	OverLimit   int `json:"overLimit"`
	Unavailable int `json:"unavailable"`
	Blocking    int `json:"blocking"`
	MissingItem int `json:"missingItem"`
}

type ManageLibrary struct {
	ID              int64                    `json:"id"`
	Name            string                   `json:"name"`
	RootPath        string                   `json:"rootPath"`
	Enabled         bool                     `json:"enabled"`
	ReadOnly        bool                     `json:"readOnly"`
	CaptureTimezone string                   `json:"captureTimezone"`
	Rules           []*ManageRecognitionRule `json:"rules"`
}

type ManageMaintenanceState struct {
	State           string  `json:"state"`
	RestoreBackupID *string `json:"restoreBackupID,omitempty"`
	LastErrorCode   string  `json:"lastErrorCode"`
	UpdatedAt       string  `json:"updatedAt"`
}

type ManageManifestConflict struct {
	Path         string `json:"path"`
	BaselineJSON string `json:"baselineJSON"`
	DatabaseJSON string `json:"databaseJSON"`
	FileJSON     string `json:"fileJSON"`
}

type ManageMediaClassificationEvaluation struct {
	Evaluated  int `json:"evaluated"`
	Matched    int `json:"matched"`
	Pending    int `json:"pending"`
	Superseded int `json:"superseded"`
}

type ManageMediaClassificationMatch struct {
	Matched        bool           `json:"matched"`
	RuleID         int64          `json:"ruleID"`
	RuleName       string         `json:"ruleName"`
	ResultCategory *ImageCategory `json:"resultCategory,omitempty"`
	Subject        string         `json:"subject"`
	MatchedValue   string         `json:"matchedValue"`
}

type ManageMediaClassificationPreview struct {
	TotalMatches int                                       `json:"totalMatches"`
	Samples      []*ManageMediaClassificationPreviewSample `json:"samples"`
}

type ManageMediaClassificationPreviewSample struct {
	GallerySetID     string        `json:"gallerySetID"`
	GalleryTitle     string        `json:"galleryTitle"`
	ItemUUID         string        `json:"itemUUID"`
	RelativePath     string        `json:"relativePath"`
	CurrentCategory  ImageCategory `json:"currentCategory"`
	ProposedCategory ImageCategory `json:"proposedCategory"`
	MatchedValue     string        `json:"matchedValue"`
}

type ManageMediaClassificationRule struct {
	ID             int64         `json:"id"`
	LibraryID      *int64        `json:"libraryID,omitempty"`
	Name           string        `json:"name"`
	Enabled        bool          `json:"enabled"`
	Order          int           `json:"order"`
	Subject        string        `json:"subject"`
	Operator       string        `json:"operator"`
	Pattern        string        `json:"pattern"`
	CaseSensitive  bool          `json:"caseSensitive"`
	ResultCategory ImageCategory `json:"resultCategory"`
	Revision       int           `json:"revision"`
	SystemDefault  bool          `json:"systemDefault"`
}

type ManageMediaClassificationSuggestion struct {
	ID               int64         `json:"id"`
	GalleryID        int64         `json:"galleryID"`
	GalleryRevision  int64         `json:"galleryRevision"`
	GallerySetID     string        `json:"gallerySetID"`
	GalleryTitle     string        `json:"galleryTitle"`
	ItemUUID         string        `json:"itemUUID"`
	RelativePath     string        `json:"relativePath"`
	RuleID           int64         `json:"ruleID"`
	RuleRevision     int           `json:"ruleRevision"`
	RuleName         string        `json:"ruleName"`
	ProposedCategory ImageCategory `json:"proposedCategory"`
	MatchedSubject   string        `json:"matchedSubject"`
	MatchedValue     string        `json:"matchedValue"`
	Status           string        `json:"status"`
}

type ManageProcessingJob struct {
	ID                int64   `json:"id"`
	Kind              string  `json:"kind"`
	GalleryID         *int64  `json:"galleryID,omitempty"`
	ItemUUID          *string `json:"itemUUID,omitempty"`
	Variant           string  `json:"variant"`
	Status            string  `json:"status"`
	Priority          int     `json:"priority"`
	AttemptCount      int     `json:"attemptCount"`
	MaxAttempts       int     `json:"maxAttempts"`
	LastErrorCode     string  `json:"lastErrorCode"`
	StructuralFailure bool    `json:"structuralFailure"`
	CreatedAt         string  `json:"createdAt"`
	UpdatedAt         string  `json:"updatedAt"`
}

type ManageProcessingJobPage struct {
	Items      []*ManageProcessingJob `json:"items"`
	Page       int                    `json:"page"`
	PageSize   int                    `json:"pageSize"`
	TotalItems int                    `json:"totalItems"`
	TotalPages int                    `json:"totalPages"`
}

type ManageRecognitionRule struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	Kind            string `json:"kind"`
	Enabled         bool   `json:"enabled"`
	AutoCreateDraft bool   `json:"autoCreateDraft"`
	Order           int    `json:"order"`
	Pattern         string `json:"pattern"`
	FixedDepth      int    `json:"fixedDepth"`
}

type ManageRuleValidation struct {
	Valid     bool   `json:"valid"`
	ErrorCode string `json:"errorCode"`
	Message   string `json:"message"`
}

type ManageRuntimeSettings struct {
	SettingsRevision                int64       `json:"settingsRevision"`
	HomeScope                       BrowseScope `json:"homeScope"`
	GalleryCardScrubberEnabled      bool        `json:"galleryCardScrubberEnabled"`
	GalleryDetailMediaFilterEnabled bool        `json:"galleryDetailMediaFilterEnabled"`
	GalleryCardControlsVisible      bool        `json:"galleryCardControlsVisible"`
	MediaCardControlsVisible        bool        `json:"mediaCardControlsVisible"`
	DetailPersonalControlsVisible   bool        `json:"detailPersonalControlsVisible"`
	GalleryAnimatedPlaybackLimit    int         `json:"galleryAnimatedPlaybackLimit"`
	GalleryAnimatedLockIntervalMs   int         `json:"galleryAnimatedLockIntervalMS"`
	RelatedLimit                    int         `json:"relatedLimit"`
	TagParentWeight                 float64     `json:"tagParentWeight"`
	TagMinimumScore                 float64     `json:"tagMinimumScore"`
	TagMaximumDepth                 int         `json:"tagMaximumDepth"`
	RandomLimit                     int         `json:"randomLimit"`
	RandomStaticQuota               float64     `json:"randomStaticQuota"`
	RandomGIFQuota                  float64     `json:"randomGIFQuota"`
	RandomVideoQuota                float64     `json:"randomVideoQuota"`
	RandomGalleryRepeatDecay        float64     `json:"randomGalleryRepeatDecay"`
	EnhancedCacheMaximumBytes       int64       `json:"enhancedCacheMaximumBytes"`
	MinimumFreeBytes                int64       `json:"minimumFreeBytes"`
	MinimumFreePercent              float64     `json:"minimumFreePercent"`
	AutomaticScanEnabled            bool        `json:"automaticScanEnabled"`
	AutomaticSchedulesSuspended     bool        `json:"automaticSchedulesSuspended"`
	DailyBackupEnabled              bool        `json:"dailyBackupEnabled"`
	DailyBackupRetention            int         `json:"dailyBackupRetention"`
	ArchiveMaxEntries               int         `json:"archiveMaxEntries"`
	ArchiveMaxEntryBytes            int64       `json:"archiveMaxEntryBytes"`
	ArchiveMaxTotalBytes            int64       `json:"archiveMaxTotalBytes"`
	ArchiveMaxCompressionRatio      float64     `json:"archiveMaxCompressionRatio"`
	ArchiveMaxImagePixels           int64       `json:"archiveMaxImagePixels"`
}

type ManageSocialAccount struct {
	UUID        string `json:"uuid"`
	PlatformKey string `json:"platformKey"`
	Label       string `json:"label"`
	Handle      string `json:"handle"`
	URL         string `json:"url"`
	Status      string `json:"status"`
	Visible     bool   `json:"visible"`
	Position    string `json:"position"`
}

type ManageSuggestion struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

type ManageUnassignedDiagnostic struct {
	ParentPath string `json:"parentPath"`
	MediaCount int    `json:"mediaCount"`
}

type ManageVideoDependencyStatus struct {
	FfmpegAvailable  bool   `json:"ffmpegAvailable"`
	FfmpegSource     string `json:"ffmpegSource"`
	FfmpegVersion    string `json:"ffmpegVersion"`
	FfmpegErrorCode  string `json:"ffmpegErrorCode"`
	FfprobeAvailable bool   `json:"ffprobeAvailable"`
	FfprobeSource    string `json:"ffprobeSource"`
	FfprobeVersion   string `json:"ffprobeVersion"`
	FfprobeErrorCode string `json:"ffprobeErrorCode"`
}

type ManifestConflictChoiceInput struct {
	Path   string `json:"path"`
	Choice string `json:"choice"`
}

type MediaClassificationRuleInput struct {
	LibraryID      *int64        `json:"libraryID,omitempty"`
	Name           string        `json:"name"`
	Enabled        bool          `json:"enabled"`
	Order          int           `json:"order"`
	Subject        string        `json:"subject"`
	Operator       string        `json:"operator"`
	Pattern        string        `json:"pattern"`
	CaseSensitive  bool          `json:"caseSensitive"`
	ResultCategory ImageCategory `json:"resultCategory"`
}

type MediaCounts struct {
	Photo  int `json:"photo"`
	Selfie int `json:"selfie"`
	Gif    int `json:"gif"`
	Video  int `json:"video"`
}

type MediaDetail struct {
	Item             *GalleryMember         `json:"item"`
	DisplayResource  *ResourceIdentity      `json:"displayResource,omitempty"`
	Gallery          *BrowseGalleryCard     `json:"gallery"`
	MetadataRevision int64                  `json:"metadataRevision"`
	VideoTechnical   *VideoTechnicalSummary `json:"videoTechnical,omitempty"`
}

type MediaInformationEntry struct {
	Key           string `json:"key"`
	VisibilityKey string `json:"visibilityKey"`
	Label         string `json:"label"`
	Group         string `json:"group"`
	Value         string `json:"value"`
}

type MediaInformationSummary struct {
	State     string                   `json:"state"`
	ErrorCode string                   `json:"errorCode"`
	Entries   []*MediaInformationEntry `json:"entries"`
}

type MediaPage struct {
	Items      []*RandomMediaItem `json:"items"`
	Page       int                `json:"page"`
	PageSize   int                `json:"pageSize"`
	TotalItems int                `json:"totalItems"`
	TotalPages int                `json:"totalPages"`
}

type Mutation struct {
}

type OnDemandResource struct {
	Status    ProcessingState   `json:"status"`
	Resource  *ResourceIdentity `json:"resource,omitempty"`
	ErrorCode string            `json:"errorCode"`
}

type PersonSummary struct {
	UUID      string  `json:"uuid"`
	Name      string  `json:"name"`
	AvatarURL *string `json:"avatarURL,omitempty"`
}

type PersonalStateResult struct {
	MetadataRevision int64 `json:"metadataRevision"`
}

type Query struct {
}

type RandomMediaItem struct {
	ItemUUID        string            `json:"itemUUID"`
	MediaKind       MediaKind         `json:"mediaKind"`
	ImageCategory   *ImageCategory    `json:"imageCategory,omitempty"`
	Resource        *ResourceIdentity `json:"resource"`
	GallerySetID    string            `json:"gallerySetID"`
	GallerySlug     string            `json:"gallerySlug"`
	Characters      []*EntitySummary  `json:"characters"`
	Cosers          []*EntitySummary  `json:"cosers"`
	Favorite        bool              `json:"favorite"`
	RatingHalfSteps *int              `json:"ratingHalfSteps,omitempty"`
}

type ReplaceGalleryCastInput struct {
	CharacterUUID string `json:"characterUUID"`
	Position      string `json:"position"`
}

type ReplaceGalleryCreditInput struct {
	CoserUUID string                     `json:"coserUUID"`
	Position  string                     `json:"position"`
	Cast      []*ReplaceGalleryCastInput `json:"cast"`
}

type ReplaceGalleryRelationsInput struct {
	Credits []*ReplaceGalleryCreditInput `json:"credits"`
	Tags    []*ReplaceGalleryTagInput    `json:"tags"`
}

type ReplaceGalleryTagInput struct {
	TagUUID  string `json:"tagUUID"`
	Position string `json:"position"`
}

type ReplaceTagParentInput struct {
	UUID     string `json:"uuid"`
	Position string `json:"position"`
}

type ResourceIdentity struct {
	ItemUUID        string `json:"itemUUID"`
	ContentRevision int64  `json:"contentRevision"`
	ProfileHash     string `json:"profileHash"`
	Variant         string `json:"variant"`
	MimeType        string `json:"mimeType"`
}

type RuntimeSettingsInput struct {
	HomeScope                       BrowseScope `json:"homeScope"`
	GalleryCardScrubberEnabled      bool        `json:"galleryCardScrubberEnabled"`
	GalleryDetailMediaFilterEnabled bool        `json:"galleryDetailMediaFilterEnabled"`
	GalleryCardControlsVisible      bool        `json:"galleryCardControlsVisible"`
	MediaCardControlsVisible        bool        `json:"mediaCardControlsVisible"`
	DetailPersonalControlsVisible   bool        `json:"detailPersonalControlsVisible"`
	GalleryAnimatedPlaybackLimit    int         `json:"galleryAnimatedPlaybackLimit"`
	GalleryAnimatedLockIntervalMs   int         `json:"galleryAnimatedLockIntervalMS"`
	RelatedLimit                    int         `json:"relatedLimit"`
	TagParentWeight                 float64     `json:"tagParentWeight"`
	TagMinimumScore                 float64     `json:"tagMinimumScore"`
	TagMaximumDepth                 int         `json:"tagMaximumDepth"`
	RandomLimit                     int         `json:"randomLimit"`
	RandomStaticQuota               float64     `json:"randomStaticQuota"`
	RandomGIFQuota                  float64     `json:"randomGIFQuota"`
	RandomVideoQuota                float64     `json:"randomVideoQuota"`
	RandomGalleryRepeatDecay        float64     `json:"randomGalleryRepeatDecay"`
	EnhancedCacheMaximumBytes       int64       `json:"enhancedCacheMaximumBytes"`
	MinimumFreeBytes                int64       `json:"minimumFreeBytes"`
	MinimumFreePercent              float64     `json:"minimumFreePercent"`
	AutomaticScanEnabled            bool        `json:"automaticScanEnabled"`
	AutomaticSchedulesSuspended     bool        `json:"automaticSchedulesSuspended"`
	DailyBackupEnabled              bool        `json:"dailyBackupEnabled"`
	DailyBackupRetention            int         `json:"dailyBackupRetention"`
	ArchiveMaxEntries               int         `json:"archiveMaxEntries"`
	ArchiveMaxEntryBytes            int64       `json:"archiveMaxEntryBytes"`
	ArchiveMaxTotalBytes            int64       `json:"archiveMaxTotalBytes"`
	ArchiveMaxCompressionRatio      float64     `json:"archiveMaxCompressionRatio"`
	ArchiveMaxImagePixels           int64       `json:"archiveMaxImagePixels"`
}

type SearchHit struct {
	Kind       SearchEntityKind `json:"kind"`
	UUID       string           `json:"uuid"`
	Slug       string           `json:"slug"`
	Name       string           `json:"name"`
	MatchLevel int              `json:"matchLevel"`
}

type SearchPreview struct {
	Scope      BrowseScope  `json:"scope"`
	Query      string       `json:"query"`
	Galleries  []*SearchHit `json:"galleries"`
	Cosers     []*SearchHit `json:"cosers"`
	Works      []*SearchHit `json:"works"`
	Characters []*SearchHit `json:"characters"`
	Tags       []*SearchHit `json:"tags"`
}

type SocialAccount struct {
	UUID        string `json:"uuid"`
	PlatformKey string `json:"platformKey"`
	Label       string `json:"label"`
	Handle      string `json:"handle"`
	URL         string `json:"url"`
	Status      string `json:"status"`
	Position    string `json:"position"`
}

type SocialAccountInput struct {
	PlatformKey string `json:"platformKey"`
	Label       string `json:"label"`
	Handle      string `json:"handle"`
	URL         string `json:"url"`
	Status      string `json:"status"`
	Visible     bool   `json:"visible"`
	Position    string `json:"position"`
}

type TagDetail struct {
	Entity     *EntityIndexItem `json:"entity"`
	Galleries  *GalleryPage     `json:"galleries"`
	Redirected bool             `json:"redirected"`
}

type UpdateGalleryItemInput struct {
	ImageCategory *ImageCategory `json:"imageCategory,omitempty"`
	Caption       string         `json:"caption"`
}

type UpdateGalleryMetadataInput struct {
	Title              string             `json:"title"`
	Aliases            []string           `json:"aliases"`
	Description        string             `json:"description"`
	ShootDate          string             `json:"shootDate"`
	ShootDatePrecision ShootDatePrecision `json:"shootDatePrecision"`
	ContentRating      ContentRating      `json:"contentRating"`
	PhotographerName   string             `json:"photographerName"`
	StudioName         string             `json:"studioName"`
}

type UpdateMediaClassificationRuleInput struct {
	ID             int64         `json:"id"`
	LibraryID      *int64        `json:"libraryID,omitempty"`
	Name           string        `json:"name"`
	Enabled        bool          `json:"enabled"`
	Order          int           `json:"order"`
	Subject        string        `json:"subject"`
	Operator       string        `json:"operator"`
	Pattern        string        `json:"pattern"`
	CaseSensitive  bool          `json:"caseSensitive"`
	ResultCategory ImageCategory `json:"resultCategory"`
}

type UpdateRecognitionRuleInput struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	Kind            string `json:"kind"`
	Enabled         bool   `json:"enabled"`
	AutoCreateDraft bool   `json:"autoCreateDraft"`
	Order           int    `json:"order"`
	Pattern         string `json:"pattern"`
	FixedDepth      int    `json:"fixedDepth"`
}

type VideoPlaybackStatus struct {
	ItemUUID        string            `json:"itemUUID"`
	Mode            string            `json:"mode"`
	Status          ProcessingState   `json:"status"`
	ContentRevision int64             `json:"contentRevision"`
	Resource        *ResourceIdentity `json:"resource,omitempty"`
	ErrorCode       string            `json:"errorCode"`
}

type VideoTechnicalSummary struct {
	ProbeState      string  `json:"probeState"`
	ErrorCode       string  `json:"errorCode"`
	Container       string  `json:"container"`
	DurationSeconds float64 `json:"durationSeconds"`
	Width           int     `json:"width"`
	Height          int     `json:"height"`
	FrameRate       float64 `json:"frameRate"`
	VideoCodec      string  `json:"videoCodec"`
	AudioCodec      string  `json:"audioCodec"`
}

type WorkDetail struct {
	Entity     *EntityIndexItem   `json:"entity"`
	Characters []*EntityIndexItem `json:"characters"`
	Redirected bool               `json:"redirected"`
}

type BrowseScope string

const (
	BrowseScopeList  BrowseScope = "LIST"
	BrowseScopeMagic BrowseScope = "MAGIC"
	BrowseScopeAll   BrowseScope = "ALL"
)

var AllBrowseScope = []BrowseScope{
	BrowseScopeList,
	BrowseScopeMagic,
	BrowseScopeAll,
}

func (e BrowseScope) IsValid() bool {
	switch e {
	case BrowseScopeList, BrowseScopeMagic, BrowseScopeAll:
		return true
	}
	return false
}

func (e BrowseScope) String() string {
	return string(e)
}

func (e *BrowseScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BrowseScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BrowseScope", str)
	}
	return nil
}

func (e BrowseScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BrowseScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BrowseScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CollectionType string

const (
	CollectionTypeAlbum   CollectionType = "ALBUM"
	CollectionTypeCosplay CollectionType = "COSPLAY"
)

var AllCollectionType = []CollectionType{
	CollectionTypeAlbum,
	CollectionTypeCosplay,
}

func (e CollectionType) IsValid() bool {
	switch e {
	case CollectionTypeAlbum, CollectionTypeCosplay:
		return true
	}
	return false
}

func (e CollectionType) String() string {
	return string(e)
}

func (e *CollectionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CollectionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CollectionType", str)
	}
	return nil
}

func (e CollectionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CollectionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CollectionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ContentFormat string

const (
	ContentFormatImage ContentFormat = "IMAGE"
	ContentFormatVideo ContentFormat = "VIDEO"
	ContentFormatRaw   ContentFormat = "RAW"
)

var AllContentFormat = []ContentFormat{
	ContentFormatImage,
	ContentFormatVideo,
	ContentFormatRaw,
}

func (e ContentFormat) IsValid() bool {
	switch e {
	case ContentFormatImage, ContentFormatVideo, ContentFormatRaw:
		return true
	}
	return false
}

func (e ContentFormat) String() string {
	return string(e)
}

func (e *ContentFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentFormat", str)
	}
	return nil
}

func (e ContentFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContentFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContentFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ContentRating string

const (
	ContentRatingNonAdult ContentRating = "NON_ADULT"
	ContentRatingAdult    ContentRating = "ADULT"
)

var AllContentRating = []ContentRating{
	ContentRatingNonAdult,
	ContentRatingAdult,
}

func (e ContentRating) IsValid() bool {
	switch e {
	case ContentRatingNonAdult, ContentRatingAdult:
		return true
	}
	return false
}

func (e ContentRating) String() string {
	return string(e)
}

func (e *ContentRating) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentRating(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentRating", str)
	}
	return nil
}

func (e ContentRating) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContentRating) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContentRating) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EntitySort string

const (
	EntitySortName          EntitySort = "NAME"
	EntitySortRecentlyAdded EntitySort = "RECENTLY_ADDED"
)

var AllEntitySort = []EntitySort{
	EntitySortName,
	EntitySortRecentlyAdded,
}

func (e EntitySort) IsValid() bool {
	switch e {
	case EntitySortName, EntitySortRecentlyAdded:
		return true
	}
	return false
}

func (e EntitySort) String() string {
	return string(e)
}

func (e *EntitySort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntitySort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntitySort", str)
	}
	return nil
}

func (e EntitySort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntitySort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntitySort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GallerySort string

const (
	GallerySortRecentlyAdded GallerySort = "RECENTLY_ADDED"
	GallerySortName          GallerySort = "NAME"
	GallerySortShootDate     GallerySort = "SHOOT_DATE"
	GallerySortRating        GallerySort = "RATING"
)

var AllGallerySort = []GallerySort{
	GallerySortRecentlyAdded,
	GallerySortName,
	GallerySortShootDate,
	GallerySortRating,
}

func (e GallerySort) IsValid() bool {
	switch e {
	case GallerySortRecentlyAdded, GallerySortName, GallerySortShootDate, GallerySortRating:
		return true
	}
	return false
}

func (e GallerySort) String() string {
	return string(e)
}

func (e *GallerySort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GallerySort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GallerySort", str)
	}
	return nil
}

func (e GallerySort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GallerySort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GallerySort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GalleryState string

const (
	GalleryStateDraft    GalleryState = "DRAFT"
	GalleryStateActive   GalleryState = "ACTIVE"
	GalleryStateArchived GalleryState = "ARCHIVED"
)

var AllGalleryState = []GalleryState{
	GalleryStateDraft,
	GalleryStateActive,
	GalleryStateArchived,
}

func (e GalleryState) IsValid() bool {
	switch e {
	case GalleryStateDraft, GalleryStateActive, GalleryStateArchived:
		return true
	}
	return false
}

func (e GalleryState) String() string {
	return string(e)
}

func (e *GalleryState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GalleryState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GalleryState", str)
	}
	return nil
}

func (e GalleryState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GalleryState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GalleryState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImageCategory string

const (
	ImageCategoryPhoto  ImageCategory = "PHOTO"
	ImageCategorySelfie ImageCategory = "SELFIE"
)

var AllImageCategory = []ImageCategory{
	ImageCategoryPhoto,
	ImageCategorySelfie,
}

func (e ImageCategory) IsValid() bool {
	switch e {
	case ImageCategoryPhoto, ImageCategorySelfie:
		return true
	}
	return false
}

func (e ImageCategory) String() string {
	return string(e)
}

func (e *ImageCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImageCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImageCategory", str)
	}
	return nil
}

func (e ImageCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImageCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImageCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaKind string

const (
	MediaKindStaticImage   MediaKind = "STATIC_IMAGE"
	MediaKindAnimatedImage MediaKind = "ANIMATED_IMAGE"
	MediaKindVideo         MediaKind = "VIDEO"
)

var AllMediaKind = []MediaKind{
	MediaKindStaticImage,
	MediaKindAnimatedImage,
	MediaKindVideo,
}

func (e MediaKind) IsValid() bool {
	switch e {
	case MediaKindStaticImage, MediaKindAnimatedImage, MediaKindVideo:
		return true
	}
	return false
}

func (e MediaKind) String() string {
	return string(e)
}

func (e *MediaKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaKind", str)
	}
	return nil
}

func (e MediaKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProcessingState string

const (
	ProcessingStatePending    ProcessingState = "PENDING"
	ProcessingStateProcessing ProcessingState = "PROCESSING"
	ProcessingStateReady      ProcessingState = "READY"
	ProcessingStateError      ProcessingState = "ERROR"
)

var AllProcessingState = []ProcessingState{
	ProcessingStatePending,
	ProcessingStateProcessing,
	ProcessingStateReady,
	ProcessingStateError,
}

func (e ProcessingState) IsValid() bool {
	switch e {
	case ProcessingStatePending, ProcessingStateProcessing, ProcessingStateReady, ProcessingStateError:
		return true
	}
	return false
}

func (e ProcessingState) String() string {
	return string(e)
}

func (e *ProcessingState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProcessingState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProcessingState", str)
	}
	return nil
}

func (e ProcessingState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProcessingState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProcessingState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RandomMediaFilter string

const (
	RandomMediaFilterAll    RandomMediaFilter = "ALL"
	RandomMediaFilterPhoto  RandomMediaFilter = "PHOTO"
	RandomMediaFilterSelfie RandomMediaFilter = "SELFIE"
	RandomMediaFilterGif    RandomMediaFilter = "GIF"
	RandomMediaFilterVideo  RandomMediaFilter = "VIDEO"
)

var AllRandomMediaFilter = []RandomMediaFilter{
	RandomMediaFilterAll,
	RandomMediaFilterPhoto,
	RandomMediaFilterSelfie,
	RandomMediaFilterGif,
	RandomMediaFilterVideo,
}

func (e RandomMediaFilter) IsValid() bool {
	switch e {
	case RandomMediaFilterAll, RandomMediaFilterPhoto, RandomMediaFilterSelfie, RandomMediaFilterGif, RandomMediaFilterVideo:
		return true
	}
	return false
}

func (e RandomMediaFilter) String() string {
	return string(e)
}

func (e *RandomMediaFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RandomMediaFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RandomMediaFilter", str)
	}
	return nil
}

func (e RandomMediaFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RandomMediaFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RandomMediaFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchEntityKind string

const (
	SearchEntityKindGallery   SearchEntityKind = "GALLERY"
	SearchEntityKindCoser     SearchEntityKind = "COSER"
	SearchEntityKindWork      SearchEntityKind = "WORK"
	SearchEntityKindCharacter SearchEntityKind = "CHARACTER"
	SearchEntityKindTag       SearchEntityKind = "TAG"
)

var AllSearchEntityKind = []SearchEntityKind{
	SearchEntityKindGallery,
	SearchEntityKindCoser,
	SearchEntityKindWork,
	SearchEntityKindCharacter,
	SearchEntityKindTag,
}

func (e SearchEntityKind) IsValid() bool {
	switch e {
	case SearchEntityKindGallery, SearchEntityKindCoser, SearchEntityKindWork, SearchEntityKindCharacter, SearchEntityKindTag:
		return true
	}
	return false
}

func (e SearchEntityKind) String() string {
	return string(e)
}

func (e *SearchEntityKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchEntityKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchEntityKind", str)
	}
	return nil
}

func (e SearchEntityKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchEntityKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchEntityKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ShootDatePrecision string

const (
	ShootDatePrecisionDay     ShootDatePrecision = "DAY"
	ShootDatePrecisionMonth   ShootDatePrecision = "MONTH"
	ShootDatePrecisionUnknown ShootDatePrecision = "UNKNOWN"
)

var AllShootDatePrecision = []ShootDatePrecision{
	ShootDatePrecisionDay,
	ShootDatePrecisionMonth,
	ShootDatePrecisionUnknown,
}

func (e ShootDatePrecision) IsValid() bool {
	switch e {
	case ShootDatePrecisionDay, ShootDatePrecisionMonth, ShootDatePrecisionUnknown:
		return true
	}
	return false
}

func (e ShootDatePrecision) String() string {
	return string(e)
}

func (e *ShootDatePrecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShootDatePrecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShootDatePrecision", str)
	}
	return nil
}

func (e ShootDatePrecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShootDatePrecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShootDatePrecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
