package productapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"time"

	"github.com/stashapp/stash/internal/archivecheck"
	"github.com/stashapp/stash/internal/browse"
	"github.com/stashapp/stash/internal/coreentity"
	"github.com/stashapp/stash/internal/discovery"
	"github.com/stashapp/stash/internal/gallery"
	"github.com/stashapp/stash/internal/manifest"
	"github.com/stashapp/stash/internal/persistence/productdb"
	"github.com/stashapp/stash/internal/portableid"
	"github.com/stashapp/stash/internal/settings"
)

// SetGalleryFavorite is the resolver for the setGalleryFavorite field.
func (r *mutationResolver) SetGalleryFavorite(ctx context.Context, setID string, favorite bool) (*PersonalStateResult, error) {
	if err := r.Database.PersonalStates().SetGalleryFavoriteBySetID(ctx, setID, favorite, time.Now()); err != nil {
		return nil, publicError(err)
	}
	var revision int64
	if err := r.Database.QueryRowContext(ctx, `SELECT metadata_revision FROM galleries WHERE set_id=?`, setID).Scan(&revision); err != nil {
		return nil, publicError(err)
	}
	return &PersonalStateResult{MetadataRevision: revision}, nil
}

// SetGalleryRating is the resolver for the setGalleryRating field.
func (r *mutationResolver) SetGalleryRating(ctx context.Context, setID string, ratingHalfSteps *int, expectedMetadataRevision int64) (*PersonalStateResult, error) {
	revision, err := r.Database.PersonalStates().SetGalleryRatingBySetID(ctx, setID, ratingHalfSteps, expectedMetadataRevision, time.Now())
	if err != nil {
		return nil, publicError(err)
	}
	return &PersonalStateResult{MetadataRevision: revision}, nil
}

// SetItemFavorite is the resolver for the setItemFavorite field.
func (r *mutationResolver) SetItemFavorite(ctx context.Context, itemUUID string, favorite bool) (*PersonalStateResult, error) {
	if err := r.Database.PersonalStates().SetItemFavoriteByUUID(ctx, itemUUID, favorite, time.Now()); err != nil {
		return nil, publicError(err)
	}
	var revision int64
	if err := r.Database.QueryRowContext(ctx, `SELECT gallery.metadata_revision FROM gallery_items item JOIN galleries gallery ON gallery.id=item.gallery_id WHERE item.item_uuid=?`, itemUUID).Scan(&revision); err != nil {
		return nil, publicError(err)
	}
	return &PersonalStateResult{MetadataRevision: revision}, nil
}

// SetItemRating is the resolver for the setItemRating field.
func (r *mutationResolver) SetItemRating(ctx context.Context, itemUUID string, ratingHalfSteps *int, expectedMetadataRevision int64) (*PersonalStateResult, error) {
	revision, err := r.Database.PersonalStates().SetItemRatingByUUID(ctx, itemUUID, ratingHalfSteps, expectedMetadataRevision, time.Now())
	if err != nil {
		return nil, publicError(err)
	}
	return &PersonalStateResult{MetadataRevision: revision}, nil
}

// RecordGalleryView is the resolver for the recordGalleryView field.
func (r *mutationResolver) RecordGalleryView(ctx context.Context, setID string, itemUUID *string) (bool, error) {
	if err := r.Database.PersonalStates().RecordGalleryViewBySetID(ctx, setID, itemUUID, time.Now()); err != nil {
		return false, publicError(err)
	}
	return true, nil
}

// UpdateGalleryMetadata is the resolver for the updateGalleryMetadata field.
func (r *mutationResolver) UpdateGalleryMetadata(ctx context.Context, setID string, expectedMetadataRevision int64, input UpdateGalleryMetadataInput) (*ManageGalleryDetail, error) {
	id, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	precision := gallery.ShootDatePrecision(input.ShootDatePrecision)
	if input.ShootDatePrecision == ShootDatePrecisionUnknown {
		precision = ""
	}
	_, err = r.Database.Galleries().UpdateMetadata(ctx, id, expectedMetadataRevision, productdb.UpdateGalleryMetadataInput{
		Title: input.Title, Aliases: input.Aliases, Description: input.Description, ShootDate: input.ShootDate,
		ShootDatePrecision: precision, ContentRating: gallery.ContentRating(input.ContentRating),
		PhotographerName: input.PhotographerName, StudioName: input.StudioName}, time.Now())
	if err != nil {
		return nil, manageError(err)
	}
	value, err := r.Database.Manage().GalleryDetail(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageGalleryDetail(value), nil
}

// SetGalleryState is the resolver for the setGalleryState field.
func (r *mutationResolver) SetGalleryState(ctx context.Context, setID string, expectedMetadataRevision int64, state GalleryState) (*ManageGalleryDetail, error) {
	id, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		r.auditManage(ctx, "GALLERY_STATE_CHANGE", "GALLERY", setID, "GALLERY_STATE_FAILED", err, map[string]any{"state": state})
		return nil, manageError(err)
	}
	if _, err := r.Database.Galleries().SetState(ctx, id, expectedMetadataRevision, gallery.State(state), time.Now()); err != nil {
		r.auditManage(ctx, "GALLERY_STATE_CHANGE", "GALLERY", setID, "GALLERY_STATE_FAILED", err, map[string]any{"state": state})
		return nil, manageError(err)
	}
	r.auditManage(ctx, "GALLERY_STATE_CHANGE", "GALLERY", setID, "", nil, map[string]any{"state": state})
	value, err := r.Database.Manage().GalleryDetail(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageGalleryDetail(value), nil
}

// UpdateGalleryItem is the resolver for the updateGalleryItem field.
func (r *mutationResolver) UpdateGalleryItem(ctx context.Context, setID string, itemUUID string, expectedMetadataRevision int64, input UpdateGalleryItemInput) (*ManageGalleryDetail, error) {
	itemID, err := r.Database.Manage().GalleryItemID(ctx, setID, itemUUID)
	if err != nil {
		return nil, manageError(err)
	}
	category := gallery.ImageCategory("")
	if input.ImageCategory != nil {
		category = gallery.ImageCategory(*input.ImageCategory)
	}
	if _, err := r.Database.Galleries().UpdateItemMetadata(ctx, itemID, category, input.Caption, expectedMetadataRevision, time.Now()); err != nil {
		return nil, manageError(err)
	}
	return r.loadManageGalleryDetail(ctx, setID)
}

// SetGalleryItemExcluded is the resolver for the setGalleryItemExcluded field.
func (r *mutationResolver) SetGalleryItemExcluded(ctx context.Context, setID string, itemUUID string, excluded bool, expectedMetadataRevision int64) (*ManageGalleryDetail, error) {
	itemID, err := r.Database.Manage().GalleryItemID(ctx, setID, itemUUID)
	if err != nil {
		return nil, manageError(err)
	}
	if _, err := r.Database.Galleries().SetItemExcluded(ctx, itemID, excluded, expectedMetadataRevision, time.Now()); err != nil {
		return nil, manageError(err)
	}
	return r.loadManageGalleryDetail(ctx, setID)
}

// MoveGalleryItem is the resolver for the moveGalleryItem field.
func (r *mutationResolver) MoveGalleryItem(ctx context.Context, setID string, itemUUID string, beforeItemUUID *string, expectedMetadataRevision int64) (*ManageGalleryDetail, error) {
	itemID, err := r.Database.Manage().GalleryItemID(ctx, setID, itemUUID)
	if err != nil {
		return nil, manageError(err)
	}
	var beforeItemID *int64
	if beforeItemUUID != nil {
		value, err := r.Database.Manage().GalleryItemID(ctx, setID, *beforeItemUUID)
		if err != nil {
			return nil, manageError(err)
		}
		beforeItemID = &value
	}
	if _, err := r.Database.Galleries().MoveItemWithinGroup(ctx, itemID, beforeItemID, expectedMetadataRevision, time.Now()); err != nil {
		return nil, manageError(err)
	}
	return r.loadManageGalleryDetail(ctx, setID)
}

// SetGalleryCoverItem is the resolver for the setGalleryCoverItem field.
func (r *mutationResolver) SetGalleryCoverItem(ctx context.Context, setID string, itemUUID string, expectedMetadataRevision int64) (*ManageGalleryDetail, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	if _, err := r.Database.Manage().GalleryItemID(ctx, setID, itemUUID); err != nil {
		return nil, manageError(err)
	}
	if _, err := r.Database.Covers().SetItem(ctx, galleryID, itemUUID, expectedMetadataRevision, time.Now()); err != nil {
		return nil, manageError(err)
	}
	return r.loadManageGalleryDetail(ctx, setID)
}

// ResetGalleryCover is the resolver for the resetGalleryCover field.
func (r *mutationResolver) ResetGalleryCover(ctx context.Context, setID string, expectedMetadataRevision int64) (*ManageGalleryDetail, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	if _, err := r.Database.Covers().ResetToAuto(ctx, galleryID, expectedMetadataRevision, time.Now()); err != nil {
		return nil, manageError(err)
	}
	return r.loadManageGalleryDetail(ctx, setID)
}

// CreateMediaLibrary is the resolver for the createMediaLibrary field.
func (r *mutationResolver) CreateMediaLibrary(ctx context.Context, input CreateMediaLibraryInput) (*ManageLibrary, error) {
	value, err := r.Database.Libraries().Create(ctx, productdb.CreateLibraryInput{Name: input.Name, RootPath: input.RootPath, Enabled: input.Enabled, ReadOnly: input.ReadOnly, CaptureTimezone: input.CaptureTimezone}, time.Now())
	if err != nil {
		r.auditManage(ctx, "LIBRARY_CREATE", "LIBRARY", "", "LIBRARY_CREATE_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "LIBRARY_CREATE", "LIBRARY", strconv.FormatInt(value.ID, 10), "", nil, map[string]any{"enabled": value.Enabled, "read_only": value.ReadOnly})
	return manageLibrary(value, nil), nil
}

// CreateRecognitionRule is the resolver for the createRecognitionRule field.
func (r *mutationResolver) CreateRecognitionRule(ctx context.Context, input CreateRecognitionRuleInput) (*ManageRecognitionRule, error) {
	value, err := r.Database.RecognitionRules().Create(ctx, productdb.CreateRecognitionRuleInput{LibraryID: input.LibraryID, Name: input.Name, Kind: discovery.RuleKind(input.Kind), Enabled: input.Enabled, AutoCreateDraft: input.AutoCreateDraft, Order: input.Order, Pattern: input.Pattern, FixedDepth: input.FixedDepth}, time.Now())
	if err != nil {
		r.auditManage(ctx, "RECOGNITION_RULE_CREATE", "LIBRARY", strconv.FormatInt(input.LibraryID, 10), "RECOGNITION_RULE_CREATE_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "RECOGNITION_RULE_CREATE", "RULE", strconv.FormatInt(value.ID, 10), "", nil, map[string]any{"library_id": input.LibraryID, "kind": value.Kind, "enabled": value.Enabled, "auto_create_draft": value.AutoCreateDraft})
	return manageRecognitionRule(value), nil
}

// DiscoverMediaLibrary is the resolver for the discoverMediaLibrary field.
func (r *mutationResolver) DiscoverMediaLibrary(ctx context.Context, libraryID int64) (*ManageDiscoverySnapshot, error) {
	value, err := r.Database.CandidateDiscovery().DiscoverFilesystem(ctx, libraryID, time.Now())
	if err != nil {
		r.auditManage(ctx, "LIBRARY_DISCOVERY", "LIBRARY", strconv.FormatInt(libraryID, 10), "LIBRARY_DISCOVERY_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "LIBRARY_DISCOVERY", "LIBRARY", strconv.FormatInt(libraryID, 10), "", nil, map[string]any{"candidate_count": len(value.Candidates), "unassigned_count": len(value.Unassigned)})
	return manageDiscoverySnapshot(value), nil
}

// ImportGalleryCandidate is the resolver for the importGalleryCandidate field.
func (r *mutationResolver) ImportGalleryCandidate(ctx context.Context, candidateID int64) (*ManageGalleryDetail, error) {
	created, err := r.Database.CandidateDiscovery().ImportCandidate(ctx, candidateID, time.Now())
	if err != nil {
		r.auditManage(ctx, "GALLERY_IMPORT_DRAFT", "CANDIDATE", strconv.FormatInt(candidateID, 10), "GALLERY_IMPORT_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "GALLERY_IMPORT_DRAFT", "GALLERY", created.SetID, "", nil, map[string]any{"candidate_id": candidateID})
	return r.loadManageGalleryDetail(ctx, created.SetID)
}

// ScanGallerySource is the resolver for the scanGallerySource field.
func (r *mutationResolver) ScanGallerySource(ctx context.Context, setID string) (*ManageGalleryDetail, error) {
	sourceID, err := r.Database.Manage().GallerySourceID(ctx, setID)
	if err != nil {
		r.auditManage(ctx, "GALLERY_SOURCE_SCAN", "GALLERY", setID, "GALLERY_SCAN_FAILED", err, nil)
		return nil, manageError(err)
	}
	runtimeSettings, err := r.Database.Settings().Find(ctx)
	if err != nil {
		r.auditManage(ctx, "GALLERY_SOURCE_SCAN", "GALLERY", setID, "GALLERY_SCAN_FAILED", err, nil)
		return nil, manageError(err)
	}
	limits := archivecheck.Limits{MaxEntries: runtimeSettings.ArchiveMaxEntries, MaxEntryUncompressed: uint64(runtimeSettings.ArchiveMaxEntryBytes), MaxTotalUncompressed: uint64(runtimeSettings.ArchiveMaxTotalBytes), MaxCompressionRatio: runtimeSettings.ArchiveMaxCompressionRatio, MaxImagePixels: uint64(runtimeSettings.ArchiveMaxImagePixels)}
	if err := r.Database.Scans().Run(ctx, sourceID, limits, time.Now()); err != nil {
		r.auditManage(ctx, "GALLERY_SOURCE_SCAN", "GALLERY", setID, "GALLERY_SCAN_FAILED", err, map[string]any{"source_id": sourceID})
		return nil, manageError(err)
	}
	r.auditManage(ctx, "GALLERY_SOURCE_SCAN", "GALLERY", setID, "", nil, map[string]any{"source_id": sourceID})
	return r.loadManageGalleryDetail(ctx, setID)
}

// UpdateRuntimeSettings is the resolver for the updateRuntimeSettings field.
func (r *mutationResolver) UpdateRuntimeSettings(ctx context.Context, expectedSettingsRevision int64, input RuntimeSettingsInput) (*ManageRuntimeSettings, error) {
	value, err := r.Database.Settings().Update(ctx, expectedSettingsRevision, settings.Runtime{HomeScope: settings.HomeScope(input.HomeScope),
		GalleryCardScrubberEnabled: input.GalleryCardScrubberEnabled, GalleryDetailMediaFilterEnabled: input.GalleryDetailMediaFilterEnabled,
		GalleryCardControlsVisible: input.GalleryCardControlsVisible, MediaCardControlsVisible: input.MediaCardControlsVisible,
		DetailPersonalControlsVisible: input.DetailPersonalControlsVisible, RelatedLimit: input.RelatedLimit, TagParentWeight: input.TagParentWeight,
		TagMinimumScore: input.TagMinimumScore, TagMaximumDepth: input.TagMaximumDepth, RandomLimit: input.RandomLimit,
		RandomStaticQuota: input.RandomStaticQuota, RandomGIFQuota: input.RandomGIFQuota, RandomVideoQuota: input.RandomVideoQuota,
		RandomGalleryRepeatDecay: input.RandomGalleryRepeatDecay, EnhancedCacheMaximumBytes: input.EnhancedCacheMaximumBytes,
		MinimumFreeBytes: input.MinimumFreeBytes, MinimumFreePercent: input.MinimumFreePercent, AutomaticScanEnabled: input.AutomaticScanEnabled,
		AutomaticSchedulesSuspended: input.AutomaticSchedulesSuspended, DailyBackupEnabled: input.DailyBackupEnabled,
		DailyBackupRetention: input.DailyBackupRetention, ArchiveMaxEntries: input.ArchiveMaxEntries,
		ArchiveMaxEntryBytes: input.ArchiveMaxEntryBytes, ArchiveMaxTotalBytes: input.ArchiveMaxTotalBytes,
		ArchiveMaxCompressionRatio: input.ArchiveMaxCompressionRatio, ArchiveMaxImagePixels: input.ArchiveMaxImagePixels}, time.Now())
	if err != nil {
		r.auditManage(ctx, "RUNTIME_SETTINGS_UPDATE", "SETTINGS", "runtime", "SETTINGS_UPDATE_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "RUNTIME_SETTINGS_UPDATE", "SETTINGS", "runtime", "", nil, map[string]any{"revision": value.Revision})
	return manageRuntimeSettings(value), nil
}

// CancelProcessingJob is the resolver for the cancelProcessingJob field.
func (r *mutationResolver) CancelProcessingJob(ctx context.Context, id int64) (*ManageProcessingJobPage, error) {
	if err := r.Database.ProcessingJobs().Cancel(ctx, id, time.Now()); err != nil {
		r.auditManage(ctx, "PROCESSING_JOB_CANCEL", "JOB", strconv.FormatInt(id, 10), "JOB_CANCEL_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "PROCESSING_JOB_CANCEL", "JOB", strconv.FormatInt(id, 10), "", nil, nil)
	value, err := r.Database.ProcessingJobs().List(ctx, "ALL", 1)
	if err != nil {
		return nil, manageError(err)
	}
	return manageProcessingJobPage(value), nil
}

// RetryProcessingJob is the resolver for the retryProcessingJob field.
func (r *mutationResolver) RetryProcessingJob(ctx context.Context, id int64) (*ManageProcessingJobPage, error) {
	if _, err := r.Database.ProcessingJobs().RequeueID(ctx, id, 400, time.Now()); err != nil {
		r.auditManage(ctx, "PROCESSING_JOB_RETRY", "JOB", strconv.FormatInt(id, 10), "JOB_RETRY_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "PROCESSING_JOB_RETRY", "JOB", strconv.FormatInt(id, 10), "", nil, nil)
	value, err := r.Database.ProcessingJobs().List(ctx, "ALL", 1)
	if err != nil {
		return nil, manageError(err)
	}
	return manageProcessingJobPage(value), nil
}

// CreateFullBackup is the resolver for the createFullBackup field.
func (r *mutationResolver) CreateFullBackup(ctx context.Context) (*ManageBackupRecord, error) {
	if r.Operations == nil {
		return nil, manageError(errors.New("backup operations are unavailable"))
	}
	value, err := r.Operations.CreateFullBackup(ctx)
	if err != nil {
		return nil, manageError(err)
	}
	return manageBackupRecord(value), nil
}

// RestoreBackup is the resolver for the restoreBackup field.
func (r *mutationResolver) RestoreBackup(ctx context.Context, backupID string) (*ManageMaintenanceState, error) {
	if r.Operations == nil {
		return nil, manageError(errors.New("restore operations are unavailable"))
	}
	value, err := r.Operations.RestoreBackup(ctx, backupID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageMaintenanceState(value), nil
}

// CreateCoreEntity is the resolver for the createCoreEntity field.
func (r *mutationResolver) CreateCoreEntity(ctx context.Context, input CoreEntityInput) (*ManageCoreEntity, error) {
	named := productdb.CreateNamedEntityInput{Name: input.Name, SortName: input.SortName, Aliases: input.Aliases}
	var uuid string
	var err error
	switch input.Kind {
	case SearchEntityKindCoser:
		var value coreentity.Coser
		value, err = r.Database.CoreEntities().CreateCoser(ctx, productdb.CreateCoserInput{CreateNamedEntityInput: named, ProfileSummary: input.ProfileSummary, Biography: input.Biography, CountryOrRegion: input.CountryOrRegion}, time.Now())
		uuid = value.UUID
	case SearchEntityKindWork:
		var value coreentity.Work
		value, err = r.Database.CoreEntities().CreateWork(ctx, named, time.Now())
		uuid = value.UUID
	case SearchEntityKindCharacter:
		if input.WorkUUID == nil {
			return nil, manageError(errors.New("Character requires a Work UUID"))
		}
		var value coreentity.Character
		value, err = r.Database.CoreEntities().CreateCharacter(ctx, *input.WorkUUID, named, time.Now())
		uuid = value.UUID
	case SearchEntityKindTag:
		var value coreentity.Tag
		value, err = r.Database.CoreEntities().CreateTag(ctx, productdb.CreateTagInput{CreateNamedEntityInput: named, UseInRecommendation: input.UseInRecommendation}, time.Now())
		uuid = value.UUID
	default:
		return nil, manageError(errors.New("unsupported core entity kind"))
	}
	if err != nil {
		return nil, manageError(err)
	}
	value, err := r.Database.CoreEntities().ManageFind(ctx, string(input.Kind), uuid)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntity(value), nil
}

// UpdateCoreEntity is the resolver for the updateCoreEntity field.
func (r *mutationResolver) UpdateCoreEntity(ctx context.Context, uuid string, expectedMetadataRevision int64, input CoreEntityInput) (*ManageCoreEntity, error) {
	named := productdb.UpdateNamedEntityInput{Name: input.Name, SortName: input.SortName, Aliases: input.Aliases}
	var err error
	switch input.Kind {
	case SearchEntityKindCoser:
		current, findErr := r.Database.CoreEntities().FindCoser(ctx, uuid)
		if findErr != nil {
			return nil, manageError(findErr)
		}
		_, err = r.Database.CoreEntities().UpdateCoser(ctx, uuid, expectedMetadataRevision, productdb.UpdateCoserInput{Name: input.Name, SortName: input.SortName, Aliases: input.Aliases, ProfileSummary: input.ProfileSummary, Biography: input.Biography, CountryOrRegion: input.CountryOrRegion, AvatarPath: current.AvatarPath, BannerPath: current.BannerPath, AvatarCrop: current.AvatarCrop, BannerFocalPoint: current.BannerFocalPoint}, time.Now())
	case SearchEntityKindWork:
		_, err = r.Database.CoreEntities().UpdateWork(ctx, uuid, expectedMetadataRevision, named, time.Now())
	case SearchEntityKindCharacter:
		current, findErr := r.Database.CoreEntities().ManageFind(ctx, "CHARACTER", uuid)
		if findErr != nil {
			return nil, manageError(findErr)
		}
		if input.WorkUUID == nil || *input.WorkUUID != current.WorkUUID {
			return nil, manageError(errors.New("Character Work cannot be changed by this update"))
		}
		_, err = r.Database.CoreEntities().UpdateCharacter(ctx, uuid, expectedMetadataRevision, named, time.Now())
	case SearchEntityKindTag:
		_, err = r.Database.CoreEntities().UpdateTag(ctx, uuid, expectedMetadataRevision, productdb.UpdateTagInput{UpdateNamedEntityInput: named, UseInRecommendation: input.UseInRecommendation}, time.Now())
	default:
		return nil, manageError(errors.New("unsupported core entity kind"))
	}
	if err != nil {
		return nil, manageError(err)
	}
	value, err := r.Database.CoreEntities().ManageFind(ctx, string(input.Kind), uuid)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntity(value), nil
}

// AddCoserSocialAccount is the resolver for the addCoserSocialAccount field.
func (r *mutationResolver) AddCoserSocialAccount(ctx context.Context, coserUUID string, expectedMetadataRevision int64, input SocialAccountInput) (*ManageCoreEntity, error) {
	position, err := strconv.ParseInt(input.Position, 10, 64)
	if err != nil {
		return nil, manageError(err)
	}
	if _, err := r.Database.CoreEntities().AddSocialAccount(ctx, coserUUID, input.PlatformKey, input.Label, input.Handle, input.URL, input.Status, input.Visible, position, expectedMetadataRevision, time.Now()); err != nil {
		return nil, manageError(err)
	}
	value, err := r.Database.CoreEntities().ManageFind(ctx, "COSER", coserUUID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntity(value), nil
}

// ReplaceTagParents is the resolver for the replaceTagParents field.
func (r *mutationResolver) ReplaceTagParents(ctx context.Context, childUUID string, expectedChildRevision int64, parents []*ReplaceTagParentInput, expectedParents []*ExpectedTagRevisionInput) (*ManageCoreEntity, error) {
	convertedParents := make([]productdb.ReplaceTagParentInput, 0, len(parents))
	for _, parent := range parents {
		if parent == nil {
			return nil, manageError(errors.New("Tag parent cannot be null"))
		}
		position, err := strconv.ParseInt(parent.Position, 10, 64)
		if err != nil {
			return nil, manageError(err)
		}
		convertedParents = append(convertedParents, productdb.ReplaceTagParentInput{UUID: parent.UUID, Position: position})
	}
	convertedExpected := make([]productdb.ExpectedTagRevision, 0, len(expectedParents))
	for _, parent := range expectedParents {
		if parent == nil {
			return nil, manageError(errors.New("expected Tag revision cannot be null"))
		}
		convertedExpected = append(convertedExpected, productdb.ExpectedTagRevision{UUID: parent.UUID, MetadataRevision: parent.MetadataRevision})
	}
	if err := r.Database.CoreEntities().ReplaceTagParents(ctx, childUUID, expectedChildRevision, convertedParents, convertedExpected, time.Now()); err != nil {
		return nil, manageError(err)
	}
	value, err := r.Database.CoreEntities().ManageFind(ctx, "TAG", childUUID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntity(value), nil
}

// MergeCoreEntities is the resolver for the mergeCoreEntities field.
func (r *mutationResolver) MergeCoreEntities(ctx context.Context, kind SearchEntityKind, sourceUUID string, targetUUID string, expectedSourceRevision int64, expectedTargetRevision int64) (*ManageCoreEntityMergeResult, error) {
	portableKind, err := portableCoreKind(kind)
	if err != nil {
		return nil, manageError(err)
	}
	preview, err := r.Database.CoreEntities().Merge(ctx, portableKind, sourceUUID, targetUUID, expectedSourceRevision, expectedTargetRevision, time.Now())
	if err != nil {
		r.auditManage(ctx, "CORE_ENTITY_MERGE", string(kind), sourceUUID, "CORE_ENTITY_MERGE_FAILED", err, map[string]any{"target_uuid": targetUUID})
		return nil, manageError(err)
	}
	var completionWarning *string
	redirectStatus := "NOT_APPLICABLE"
	if portableKind == portableid.KindCoser {
		redirectStatus = "WRITTEN"
		metadataRoot, rootErr := r.coserMetadataRoot(ctx)
		if rootErr == nil {
			_, rootErr = r.Database.Manifests().WriteCoserMergeRedirect(ctx, metadataRoot, sourceUUID, targetUUID)
		}
		if rootErr != nil {
			redirectStatus = "PENDING"
			warning := "Coser redirect file is pending; the database merge committed successfully."
			completionWarning = &warning
		}
	}
	target, err := r.Database.CoreEntities().ManageFind(ctx, string(kind), targetUUID)
	if err != nil {
		return nil, manageError(err)
	}
	r.auditManage(ctx, "CORE_ENTITY_MERGE", string(kind), sourceUUID, "", nil, map[string]any{
		"target_uuid": targetUUID, "affected_gallery_count": len(preview.AffectedGalleryIDs), "coser_redirect_status": redirectStatus,
	})
	return &ManageCoreEntityMergeResult{Target: manageCoreEntity(target), Preview: manageCoreEntityMergePreview(preview), CompletionWarning: completionWarning}, nil
}

// DeleteCoreEntity is the resolver for the deleteCoreEntity field.
func (r *mutationResolver) DeleteCoreEntity(ctx context.Context, kind SearchEntityKind, uuid string, expectedMetadataRevision int64) (bool, error) {
	portableKind, err := portableCoreKind(kind)
	if err != nil {
		return false, manageError(err)
	}
	err = r.Database.CoreEntities().DeleteCoreEntity(ctx, portableKind, uuid, expectedMetadataRevision, "deleted by owner", time.Now())
	if err != nil {
		r.auditManage(ctx, "CORE_ENTITY_DELETE", string(kind), uuid, "CORE_ENTITY_DELETE_FAILED", err, nil)
		return false, manageError(err)
	}
	r.auditManage(ctx, "CORE_ENTITY_DELETE", string(kind), uuid, "", nil, nil)
	return true, nil
}

// DeleteGallery is the resolver for the deleteGallery field.
func (r *mutationResolver) DeleteGallery(ctx context.Context, setID string, expectedMetadataRevision int64, password string, confirmation string) (bool, error) {
	if confirmation != "DELETE" {
		err := errors.New("confirmation phrase does not match")
		r.auditManage(ctx, "GALLERY_DELETE", "GALLERY", setID, "GALLERY_DELETE_CONFIRMATION_FAILED", err, nil)
		return false, err
	}
	if r.OwnerPassword == nil {
		err := errors.New("owner password verification is unavailable")
		r.auditManage(ctx, "GALLERY_DELETE", "GALLERY", setID, "GALLERY_DELETE_PASSWORD_FAILED", err, nil)
		return false, err
	}
	if err := r.OwnerPassword.VerifyPassword(ctx, password); err != nil {
		r.auditManage(ctx, "GALLERY_DELETE", "GALLERY", setID, "GALLERY_DELETE_PASSWORD_FAILED", err, nil)
		return false, errors.New("owner password verification failed")
	}
	preview, err := r.Database.Galleries().PreviewDelete(ctx, setID)
	if err != nil {
		r.auditManage(ctx, "GALLERY_DELETE", "GALLERY", setID, "GALLERY_DELETE_FAILED", err, nil)
		return false, manageError(err)
	}
	if err := r.Database.Galleries().Delete(ctx, setID, expectedMetadataRevision, time.Now()); err != nil {
		r.auditManage(ctx, "GALLERY_DELETE", "GALLERY", setID, "GALLERY_DELETE_FAILED", err, nil)
		return false, manageError(err)
	}
	r.auditManage(ctx, "GALLERY_DELETE", "GALLERY", setID, "", nil, map[string]any{
		"item_count": preview.ItemCount, "external_link_count": preview.ExternalLinkCount,
		"cancelled_job_count": preview.ExecutableJobCount, "ignored_source_created": preview.HasSource,
	})
	return true, nil
}

// ReplaceGalleryRelations is the resolver for the replaceGalleryRelations field.
func (r *mutationResolver) ReplaceGalleryRelations(ctx context.Context, setID string, expectedMetadataRevision int64, input ReplaceGalleryRelationsInput) (*ManageGalleryDetail, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	converted := productdb.ReplaceGalleryRelationsInput{}
	for _, credit := range input.Credits {
		if credit == nil {
			return nil, manageError(errors.New("GalleryCredit cannot be null"))
		}
		position, err := strconv.ParseInt(credit.Position, 10, 64)
		if err != nil {
			return nil, manageError(err)
		}
		convertedCredit := productdb.ReplaceGalleryCreditInput{CoserUUID: credit.CoserUUID, Position: position}
		for _, cast := range credit.Cast {
			if cast == nil {
				return nil, manageError(errors.New("GalleryCast cannot be null"))
			}
			castPosition, err := strconv.ParseInt(cast.Position, 10, 64)
			if err != nil {
				return nil, manageError(err)
			}
			convertedCredit.Cast = append(convertedCredit.Cast, productdb.ReplaceGalleryCastInput{CharacterUUID: cast.CharacterUUID, Position: castPosition})
		}
		converted.Credits = append(converted.Credits, convertedCredit)
	}
	for _, tag := range input.Tags {
		if tag == nil {
			return nil, manageError(errors.New("GalleryTag cannot be null"))
		}
		position, err := strconv.ParseInt(tag.Position, 10, 64)
		if err != nil {
			return nil, manageError(err)
		}
		converted.Tags = append(converted.Tags, productdb.ReplaceGalleryTagInput{TagUUID: tag.TagUUID, Position: position})
	}
	if err := r.Database.Galleries().ReplaceRelations(ctx, galleryID, expectedMetadataRevision, converted, time.Now()); err != nil {
		return nil, manageError(err)
	}
	return r.loadManageGalleryDetail(ctx, setID)
}

// AddGalleryExternalLink is the resolver for the addGalleryExternalLink field.
func (r *mutationResolver) AddGalleryExternalLink(ctx context.Context, setID string, expectedMetadataRevision int64, input GalleryExternalLinkInput) (*ManageGalleryDetail, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	position, err := strconv.ParseInt(input.Position, 10, 64)
	if err != nil {
		return nil, manageError(err)
	}
	if _, err := r.Database.Galleries().AddExternalLink(ctx, galleryID, gallery.ExternalLinkType(input.Type), input.Label, input.URL, position, expectedMetadataRevision, time.Now()); err != nil {
		return nil, manageError(err)
	}
	return r.loadManageGalleryDetail(ctx, setID)
}

// PushGalleryManifest is the resolver for the pushGalleryManifest field.
func (r *mutationResolver) PushGalleryManifest(ctx context.Context, setID string, expectedMetadataRevision int64) (*ManageGalleryManifestState, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		r.auditManage(ctx, "GALLERY_MANIFEST_PUSH", "GALLERY", setID, "MANIFEST_PUSH_FAILED", err, nil)
		return nil, manageError(err)
	}
	state, err := r.Database.Manifests().PushGallery(ctx, galleryID, expectedMetadataRevision, time.Now())
	if err != nil {
		r.auditManage(ctx, "GALLERY_MANIFEST_PUSH", "GALLERY", setID, "MANIFEST_PUSH_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "GALLERY_MANIFEST_PUSH", "GALLERY", setID, "", nil, map[string]any{"manifest_revision": state.ManifestRevision})
	return r.manageGalleryManifestState(ctx, state)
}

// PullGalleryManifest is the resolver for the pullGalleryManifest field.
func (r *mutationResolver) PullGalleryManifest(ctx context.Context, setID string, expectedMetadataRevision int64) (*ManageGalleryManifestState, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		r.auditManage(ctx, "GALLERY_MANIFEST_PULL", "GALLERY", setID, "MANIFEST_PULL_FAILED", err, nil)
		return nil, manageError(err)
	}
	state, err := r.Database.Manifests().PullGallery(ctx, galleryID, expectedMetadataRevision, time.Now())
	if err != nil {
		r.auditManage(ctx, "GALLERY_MANIFEST_PULL", "GALLERY", setID, "MANIFEST_PULL_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "GALLERY_MANIFEST_PULL", "GALLERY", setID, "", nil, map[string]any{"manifest_revision": state.ManifestRevision})
	return r.manageGalleryManifestState(ctx, state)
}

// ResolveGalleryManifest is the resolver for the resolveGalleryManifest field.
func (r *mutationResolver) ResolveGalleryManifest(ctx context.Context, setID string, expectedMetadataRevision int64, choices []*ManifestConflictChoiceInput) (*ManageGalleryManifestState, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		r.auditManage(ctx, "GALLERY_MANIFEST_RESOLVE", "GALLERY", setID, "MANIFEST_RESOLVE_FAILED", err, nil)
		return nil, manageError(err)
	}
	converted := make(map[string]manifest.ConflictChoice, len(choices))
	for _, choice := range choices {
		if choice == nil || choice.Path == "" {
			return nil, manageError(errors.New("Manifest conflict choice is incomplete"))
		}
		value := manifest.ConflictChoice(choice.Choice)
		if value != manifest.ChooseDatabase && value != manifest.ChooseFile {
			return nil, manageError(errors.New("Manifest conflict choice must be DATABASE or FILE"))
		}
		if _, duplicate := converted[choice.Path]; duplicate {
			return nil, manageError(fmt.Errorf("duplicate Manifest conflict choice for %s", choice.Path))
		}
		converted[choice.Path] = value
	}
	state, err := r.Database.Manifests().ResolveGalleryConflicts(ctx, galleryID, expectedMetadataRevision, converted, time.Now())
	if err != nil {
		r.auditManage(ctx, "GALLERY_MANIFEST_RESOLVE", "GALLERY", setID, "MANIFEST_RESOLVE_FAILED", err, map[string]any{"choice_count": len(converted)})
		return nil, manageError(err)
	}
	r.auditManage(ctx, "GALLERY_MANIFEST_RESOLVE", "GALLERY", setID, "", nil, map[string]any{"choice_count": len(converted), "manifest_revision": state.ManifestRevision})
	return r.manageGalleryManifestState(ctx, state)
}

// PushCoserManifest is the resolver for the pushCoserManifest field.
func (r *mutationResolver) PushCoserManifest(ctx context.Context, coserUUID string, expectedMetadataRevision int64) (*ManageCoserManifestState, error) {
	metadataRoot, err := r.coserMetadataRoot(ctx)
	if err != nil {
		r.auditManage(ctx, "COSER_MANIFEST_PUSH", "COSER", coserUUID, "MANIFEST_PUSH_FAILED", err, nil)
		return nil, err
	}
	state, err := r.Database.Manifests().PushCoser(ctx, metadataRoot, coserUUID, expectedMetadataRevision, time.Now())
	if err != nil {
		r.auditManage(ctx, "COSER_MANIFEST_PUSH", "COSER", coserUUID, "MANIFEST_PUSH_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "COSER_MANIFEST_PUSH", "COSER", coserUUID, "", nil, map[string]any{"manifest_revision": state.ManifestRevision})
	return r.manageCoserManifestState(ctx, state)
}

// PullCoserManifest is the resolver for the pullCoserManifest field.
func (r *mutationResolver) PullCoserManifest(ctx context.Context, coserUUID string, expectedMetadataRevision int64) (*ManageCoserManifestState, error) {
	metadataRoot, err := r.coserMetadataRoot(ctx)
	if err != nil {
		r.auditManage(ctx, "COSER_MANIFEST_PULL", "COSER", coserUUID, "MANIFEST_PULL_FAILED", err, nil)
		return nil, err
	}
	state, err := r.Database.Manifests().PullCoser(ctx, metadataRoot, coserUUID, expectedMetadataRevision, time.Now())
	if err != nil {
		r.auditManage(ctx, "COSER_MANIFEST_PULL", "COSER", coserUUID, "MANIFEST_PULL_FAILED", err, nil)
		return nil, manageError(err)
	}
	r.auditManage(ctx, "COSER_MANIFEST_PULL", "COSER", coserUUID, "", nil, map[string]any{"manifest_revision": state.ManifestRevision})
	return r.manageCoserManifestState(ctx, state)
}

// ResolveCoserManifest is the resolver for the resolveCoserManifest field.
func (r *mutationResolver) ResolveCoserManifest(ctx context.Context, coserUUID string, expectedMetadataRevision int64, choices []*ManifestConflictChoiceInput) (*ManageCoserManifestState, error) {
	metadataRoot, err := r.coserMetadataRoot(ctx)
	if err != nil {
		r.auditManage(ctx, "COSER_MANIFEST_RESOLVE", "COSER", coserUUID, "MANIFEST_RESOLVE_FAILED", err, nil)
		return nil, err
	}
	converted := make(map[string]manifest.ConflictChoice, len(choices))
	for _, choice := range choices {
		if choice == nil || choice.Path == "" {
			return nil, manageError(errors.New("Manifest conflict choice is incomplete"))
		}
		value := manifest.ConflictChoice(choice.Choice)
		if value != manifest.ChooseDatabase && value != manifest.ChooseFile {
			return nil, manageError(errors.New("Manifest conflict choice must be DATABASE or FILE"))
		}
		if _, duplicate := converted[choice.Path]; duplicate {
			return nil, manageError(fmt.Errorf("duplicate Manifest conflict choice for %s", choice.Path))
		}
		converted[choice.Path] = value
	}
	state, err := r.Database.Manifests().ResolveCoserConflicts(ctx, metadataRoot, coserUUID, expectedMetadataRevision, converted, time.Now())
	if err != nil {
		r.auditManage(ctx, "COSER_MANIFEST_RESOLVE", "COSER", coserUUID, "MANIFEST_RESOLVE_FAILED", err, map[string]any{"choice_count": len(converted)})
		return nil, manageError(err)
	}
	r.auditManage(ctx, "COSER_MANIFEST_RESOLVE", "COSER", coserUUID, "", nil, map[string]any{"choice_count": len(converted), "manifest_revision": state.ManifestRevision})
	return r.manageCoserManifestState(ctx, state)
}

// HomeGalleries is the resolver for the homeGalleries field.
func (r *queryResolver) HomeGalleries(ctx context.Context, page int) (*HomeGalleryPage, error) {
	value, scope, err := r.Database.Browse().Home(ctx, page)
	if err != nil {
		return nil, publicError(err)
	}
	return &HomeGalleryPage{Scope: BrowseScope(scope), Page: galleryPage(value)}, nil
}

// BrowseGalleries is the resolver for the browseGalleries field.
func (r *queryResolver) BrowseGalleries(ctx context.Context, scope BrowseScope, page int, sort GallerySort) (*GalleryPage, error) {
	value, err := r.Database.Browse().Galleries(ctx, browse.Scope(scope), page, browse.GallerySort(sort))
	if err != nil {
		return nil, publicError(err)
	}
	return galleryPage(value), nil
}

// TimelineGalleries is the resolver for the timelineGalleries field.
func (r *queryResolver) TimelineGalleries(ctx context.Context, scope BrowseScope, page int, coserUUID *string) (*GalleryPage, error) {
	coser := ""
	if coserUUID != nil {
		coser = *coserUUID
	}
	value, err := r.Database.Browse().Timeline(ctx, browse.Scope(scope), page, coser)
	if err != nil {
		return nil, publicError(err)
	}
	return galleryPage(value), nil
}

// GalleryDetail is the resolver for the galleryDetail field.
func (r *queryResolver) GalleryDetail(ctx context.Context, slug string, scope BrowseScope) (*GalleryDetail, error) {
	value, err := r.Database.Browse().GalleryDetailBySlug(ctx, browse.Scope(scope), slug)
	if err != nil {
		return nil, publicError(err)
	}
	return galleryDetail(value), nil
}

// GalleryMemberIndex is the resolver for the galleryMemberIndex field.
func (r *queryResolver) GalleryMemberIndex(ctx context.Context, setID string) (*GalleryMemberIndex, error) {
	value, err := r.Database.Browse().GalleryMemberIndex(ctx, setID, browse.ScopeAll)
	if err != nil {
		return nil, publicError(err)
	}
	return galleryMemberIndex(value), nil
}

// RelatedGalleries is the resolver for the relatedGalleries field.
func (r *queryResolver) RelatedGalleries(ctx context.Context, setID string, scope BrowseScope) ([]*GalleryRecommendation, error) {
	strong, err := r.Database.Browse().StrongRecommendations(ctx, setID, browse.Scope(scope))
	if err != nil {
		return nil, publicError(err)
	}
	tags, err := r.Database.Browse().TagRecommendations(ctx, setID, browse.Scope(scope))
	if err != nil {
		return nil, publicError(err)
	}
	return mergeRecommendations(strong, tags), nil
}

// RandomMedia is the resolver for the randomMedia field.
func (r *queryResolver) RandomMedia(ctx context.Context, scope BrowseScope, filter RandomMediaFilter) ([]*RandomMediaItem, error) {
	values, err := r.Database.Browse().RandomItems(ctx, browse.Scope(scope), browse.RandomMediaFilter(filter))
	if err != nil {
		return nil, publicError(err)
	}
	result := make([]*RandomMediaItem, 0, len(values))
	for _, value := range values {
		result = append(result, randomMediaItem(value))
	}
	return result, nil
}

// EntityIndex is the resolver for the entityIndex field.
func (r *queryResolver) EntityIndex(ctx context.Context, kind SearchEntityKind, scope BrowseScope, page int, sort EntitySort) (*EntityPage, error) {
	value, err := r.Database.Browse().EntityIndex(ctx, browse.SearchEntityKind(kind), browse.Scope(scope), page, browse.EntitySort(sort))
	if err != nil {
		return nil, publicError(err)
	}
	return entityPage(value), nil
}

// SearchPreview is the resolver for the searchPreview field.
func (r *queryResolver) SearchPreview(ctx context.Context, query string, scope BrowseScope) (*SearchPreview, error) {
	value, err := r.Database.Browse().SearchPreview(ctx, browse.Scope(scope), query)
	if err != nil {
		return nil, publicError(err)
	}
	return searchPreviewModel(value), nil
}

// CoserDetail is the resolver for the coserDetail field.
func (r *queryResolver) CoserDetail(ctx context.Context, slug string, scope BrowseScope, page int) (*CoserDetail, error) {
	value, err := r.Database.Browse().CoserDetail(ctx, slug, browse.Scope(scope), page)
	if err != nil {
		return nil, publicError(err)
	}
	return coserDetailModel(value), nil
}

// WorkDetail is the resolver for the workDetail field.
func (r *queryResolver) WorkDetail(ctx context.Context, slug string, scope BrowseScope) (*WorkDetail, error) {
	value, err := r.Database.Browse().WorkDetail(ctx, slug, browse.Scope(scope))
	if err != nil {
		return nil, publicError(err)
	}
	return workDetailModel(value), nil
}

// CharacterDetail is the resolver for the characterDetail field.
func (r *queryResolver) CharacterDetail(ctx context.Context, slug string, scope BrowseScope, page int) (*CharacterDetail, error) {
	value, err := r.Database.Browse().CharacterDetail(ctx, slug, browse.Scope(scope), page)
	if err != nil {
		return nil, publicError(err)
	}
	return characterDetailModel(value), nil
}

// TagDetail is the resolver for the tagDetail field.
func (r *queryResolver) TagDetail(ctx context.Context, slug string, scope BrowseScope, page int) (*TagDetail, error) {
	value, err := r.Database.Browse().TagDetail(ctx, slug, browse.Scope(scope), page)
	if err != nil {
		return nil, publicError(err)
	}
	return tagDetailModel(value), nil
}

// MediaDetail is the resolver for the mediaDetail field.
func (r *queryResolver) MediaDetail(ctx context.Context, itemUUID string) (*MediaDetail, error) {
	value, err := r.Database.Browse().MediaDetail(ctx, itemUUID)
	if err != nil {
		return nil, publicError(err)
	}
	return &MediaDetail{Item: galleryMemberModel(value.Item), DisplayResource: resourceIdentity(value.DisplayResource), Gallery: galleryCard(value.Gallery), MetadataRevision: value.MetadataRevision}, nil
}

// FavoriteGalleries is the resolver for the favoriteGalleries field.
func (r *queryResolver) FavoriteGalleries(ctx context.Context, scope BrowseScope, page int) (*GalleryPage, error) {
	value, err := r.Database.Browse().FavoriteGalleries(ctx, browse.Scope(scope), page)
	if err != nil {
		return nil, publicError(err)
	}
	return galleryPage(value), nil
}

// GalleryHistory is the resolver for the galleryHistory field.
func (r *queryResolver) GalleryHistory(ctx context.Context, scope BrowseScope, page int) (*GalleryPage, error) {
	value, err := r.Database.Browse().GalleryHistory(ctx, browse.Scope(scope), page)
	if err != nil {
		return nil, publicError(err)
	}
	return galleryPage(value), nil
}

// FavoriteMedia is the resolver for the favoriteMedia field.
func (r *queryResolver) FavoriteMedia(ctx context.Context, scope BrowseScope, page int, ratingSort bool) (*MediaPage, error) {
	value, err := r.Database.Browse().FavoriteMedia(ctx, browse.Scope(scope), page, ratingSort)
	if err != nil {
		return nil, publicError(err)
	}
	return mediaPage(value), nil
}

// ManageGalleries is the resolver for the manageGalleries field.
func (r *queryResolver) ManageGalleries(ctx context.Context, page int) (*ManageGalleryPage, error) {
	value, err := r.Database.Manage().GalleryPage(ctx, page)
	if err != nil {
		return nil, manageError(err)
	}
	return manageGalleryPage(value), nil
}

// ManageGallery is the resolver for the manageGallery field.
func (r *queryResolver) ManageGallery(ctx context.Context, setID string) (*ManageGalleryDetail, error) {
	value, err := r.Database.Manage().GalleryDetail(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageGalleryDetail(value), nil
}

// ManageGalleryManifest is the resolver for the manageGalleryManifest field.
func (r *queryResolver) ManageGalleryManifest(ctx context.Context, setID string) (*ManageGalleryManifestState, error) {
	galleryID, err := r.Database.Manage().GalleryID(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	state, err := r.Database.Manifests().CheckGallery(ctx, galleryID, time.Now())
	if err != nil {
		return nil, manageError(err)
	}
	return r.manageGalleryManifestState(ctx, state)
}

// ManageCoserManifest is the resolver for the manageCoserManifest field.
func (r *queryResolver) ManageCoserManifest(ctx context.Context, coserUUID string) (*ManageCoserManifestState, error) {
	metadataRoot, err := r.coserMetadataRoot(ctx)
	if err != nil {
		return nil, err
	}
	state, err := r.Database.Manifests().CheckCoser(ctx, metadataRoot, coserUUID, time.Now())
	if err != nil {
		return nil, manageError(err)
	}
	return r.manageCoserManifestState(ctx, state)
}

// ManageLibraries is the resolver for the manageLibraries field.
func (r *queryResolver) ManageLibraries(ctx context.Context) ([]*ManageLibrary, error) {
	values, err := r.Database.Libraries().List(ctx)
	if err != nil {
		return nil, manageError(err)
	}
	result := make([]*ManageLibrary, 0, len(values))
	for _, value := range values {
		rules, err := r.Database.RecognitionRules().List(ctx, value.ID)
		if err != nil {
			return nil, manageError(err)
		}
		result = append(result, manageLibrary(value, rules))
	}
	return result, nil
}

// ManageDiscovery is the resolver for the manageDiscovery field.
func (r *queryResolver) ManageDiscovery(ctx context.Context, libraryID int64) (*ManageDiscoverySnapshot, error) {
	value, err := r.Database.CandidateDiscovery().LatestSnapshot(ctx, libraryID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageDiscoverySnapshot(value), nil
}

// ManageRuntimeSettings is the resolver for the manageRuntimeSettings field.
func (r *queryResolver) ManageRuntimeSettings(ctx context.Context) (*ManageRuntimeSettings, error) {
	value, err := r.Database.Settings().Find(ctx)
	if err != nil {
		return nil, manageError(err)
	}
	return manageRuntimeSettings(value), nil
}

// ManageProcessingJobs is the resolver for the manageProcessingJobs field.
func (r *queryResolver) ManageProcessingJobs(ctx context.Context, status string, page int) (*ManageProcessingJobPage, error) {
	value, err := r.Database.ProcessingJobs().List(ctx, status, page)
	if err != nil {
		return nil, manageError(err)
	}
	return manageProcessingJobPage(value), nil
}

// ManageBackups is the resolver for the manageBackups field.
func (r *queryResolver) ManageBackups(ctx context.Context) ([]*ManageBackupRecord, error) {
	values, err := r.Database.Backups().List(ctx)
	if err != nil {
		return nil, manageError(err)
	}
	result := make([]*ManageBackupRecord, 0, len(values))
	for _, value := range values {
		result = append(result, manageBackupRecord(value))
	}
	return result, nil
}

// ManageMaintenance is the resolver for the manageMaintenance field.
func (r *queryResolver) ManageMaintenance(ctx context.Context) (*ManageMaintenanceState, error) {
	value, err := r.Database.Operations().Maintenance(ctx)
	if err != nil {
		return nil, manageError(err)
	}
	return manageMaintenanceState(value), nil
}

// ManageAudit is the resolver for the manageAudit field.
func (r *queryResolver) ManageAudit(ctx context.Context, page int) (*ManageAuditPage, error) {
	value, err := r.Database.Operations().AuditPage(ctx, page)
	if err != nil {
		return nil, manageError(err)
	}
	return manageAuditPage(value), nil
}

// ManageCoreEntities is the resolver for the manageCoreEntities field.
func (r *queryResolver) ManageCoreEntities(ctx context.Context, kind SearchEntityKind, page int) (*ManageCoreEntityPage, error) {
	value, err := r.Database.CoreEntities().ManagePage(ctx, string(kind), page)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntityPage(value), nil
}

// ManageCoreEntity is the resolver for the manageCoreEntity field.
func (r *queryResolver) ManageCoreEntity(ctx context.Context, kind SearchEntityKind, uuid string) (*ManageCoreEntity, error) {
	value, err := r.Database.CoreEntities().ManageFind(ctx, string(kind), uuid)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntity(value), nil
}

// ManageCoreEntityOptions is the resolver for the manageCoreEntityOptions field.
func (r *queryResolver) ManageCoreEntityOptions(ctx context.Context, kind SearchEntityKind, query string, limit int) ([]*ManageCoreEntity, error) {
	values, err := r.Database.CoreEntities().ManageOptions(ctx, string(kind), query, limit)
	if err != nil {
		return nil, manageError(err)
	}
	result := make([]*ManageCoreEntity, 0, len(values))
	for _, value := range values {
		result = append(result, manageCoreEntity(value))
	}
	return result, nil
}

// PreviewCoreEntityMerge is the resolver for the previewCoreEntityMerge field.
func (r *queryResolver) PreviewCoreEntityMerge(ctx context.Context, kind SearchEntityKind, sourceUUID string, targetUUID string) (*ManageCoreEntityMergePreview, error) {
	portableKind, err := portableCoreKind(kind)
	if err != nil {
		return nil, manageError(err)
	}
	value, err := r.Database.CoreEntities().PreviewMerge(ctx, portableKind, sourceUUID, targetUUID)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntityMergePreview(value), nil
}

// PreviewCoreEntityDelete is the resolver for the previewCoreEntityDelete field.
func (r *queryResolver) PreviewCoreEntityDelete(ctx context.Context, kind SearchEntityKind, uuid string) (*ManageCoreEntityDeletePreview, error) {
	portableKind, err := portableCoreKind(kind)
	if err != nil {
		return nil, manageError(err)
	}
	value, err := r.Database.CoreEntities().PreviewDelete(ctx, portableKind, uuid)
	if err != nil {
		return nil, manageError(err)
	}
	return manageCoreEntityDeletePreview(value), nil
}

// PreviewGalleryDelete is the resolver for the previewGalleryDelete field.
func (r *queryResolver) PreviewGalleryDelete(ctx context.Context, setID string) (*ManageGalleryDeletePreview, error) {
	value, err := r.Database.Galleries().PreviewDelete(ctx, setID)
	if err != nil {
		return nil, manageError(err)
	}
	return &ManageGalleryDeletePreview{
		SetID: value.SetID, State: GalleryState(value.State), MetadataRevision: value.MetadataRevision,
		ItemCount: value.ItemCount, ExternalLinkCount: value.ExternalLinkCount,
		ExecutableJobCount: value.ExecutableJobCount, IgnoredSourceWillBeCreated: value.HasSource,
		CanDelete: value.CanDelete(),
	}, nil
}

// BrowseUISettings is the resolver for the browseUISettings field.
func (r *queryResolver) BrowseUISettings(ctx context.Context) (*BrowseUISettings, error) {
	value, err := r.Database.Settings().Find(ctx)
	if err != nil {
		return nil, publicError(err)
	}
	return &BrowseUISettings{
		SettingsRevision:           value.Revision,
		GalleryScrubberEnabled:     value.GalleryCardScrubberEnabled,
		DetailMediaFilterEnabled:   value.GalleryDetailMediaFilterEnabled,
		CardFavoriteControlVisible: value.GalleryCardControlsVisible,
		CardRatingSummaryVisible:   value.GalleryCardControlsVisible,
		DetailRatingControlVisible: value.DetailPersonalControlsVisible,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
